<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 2 Importar, organizar e sumarizar os dados | Introdução a análise de dados ambientais em R</title>
  <meta name="description" content="Este é o primeiro livro da série de livros análise de dados ambientais em R" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 2 Importar, organizar e sumarizar os dados | Introdução a análise de dados ambientais em R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Este é o primeiro livro da série de livros análise de dados ambientais em R" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 2 Importar, organizar e sumarizar os dados | Introdução a análise de dados ambientais em R" />
  
  <meta name="twitter:description" content="Este é o primeiro livro da série de livros análise de dados ambientais em R" />
  

<meta name="author" content="Wilson Souza &amp; Thiago Couto" />


<meta name="date" content="2020-11-19" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="r.html"/>
<link rel="next" href="qui-quadrado-χ.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Introdução a análise de dados ambientais em R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Prefácio</a></li>
<li class="chapter" data-level="" data-path="sobre-os-autores.html"><a href="sobre-os-autores.html"><i class="fa fa-check"></i>Sobre os autores</a></li>
<li class="chapter" data-level="1" data-path="r.html"><a href="r.html"><i class="fa fa-check"></i><b>1</b> R</a><ul>
<li class="chapter" data-level="1.1" data-path="r.html"><a href="r.html#o-que-é"><i class="fa fa-check"></i><b>1.1</b> O que é?</a></li>
<li class="chapter" data-level="1.2" data-path="r.html"><a href="r.html#porque-usá-lo-para-análise-de-dados"><i class="fa fa-check"></i><b>1.2</b> Porque usá-lo para análise de dados?</a></li>
<li class="chapter" data-level="1.3" data-path="r.html"><a href="r.html#o-rstudio"><i class="fa fa-check"></i><b>1.3</b> O RStudio</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="importar-organizar-e-sumarizar-os-dados.html"><a href="importar-organizar-e-sumarizar-os-dados.html"><i class="fa fa-check"></i><b>2</b> Importar, organizar e sumarizar os dados</a><ul>
<li class="chapter" data-level="2.1" data-path="importar-organizar-e-sumarizar-os-dados.html"><a href="importar-organizar-e-sumarizar-os-dados.html#passo-definir-o-ambiente-de-trabalho-e-importar-a-planilha-de-dados-para-o-r"><i class="fa fa-check"></i><b>2.1</b> 1° passo: Definir o ambiente de trabalho e importar a planilha de dados para o R</a><ul>
<li class="chapter" data-level="2.1.1" data-path="importar-organizar-e-sumarizar-os-dados.html"><a href="importar-organizar-e-sumarizar-os-dados.html#definir-ambiente-de-trabalho-via-linha-de-comando"><i class="fa fa-check"></i><b>2.1.1</b> Definir ambiente de trabalho via linha de comando</a></li>
<li class="chapter" data-level="2.1.2" data-path="importar-organizar-e-sumarizar-os-dados.html"><a href="importar-organizar-e-sumarizar-os-dados.html#definir-ambiente-de-trabalho-via-interface-gráfica"><i class="fa fa-check"></i><b>2.1.2</b> Definir ambiente de trabalho via interface gráfica</a></li>
<li class="chapter" data-level="2.1.3" data-path="importar-organizar-e-sumarizar-os-dados.html"><a href="importar-organizar-e-sumarizar-os-dados.html#importar-planilha-via-linha-de-comando"><i class="fa fa-check"></i><b>2.1.3</b> Importar planilha via linha de comando:</a></li>
<li class="chapter" data-level="2.1.4" data-path="importar-organizar-e-sumarizar-os-dados.html"><a href="importar-organizar-e-sumarizar-os-dados.html#importar-planilha-pela-via-interface-gráfica"><i class="fa fa-check"></i><b>2.1.4</b> Importar planilha pela via interface gráfica:</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="importar-organizar-e-sumarizar-os-dados.html"><a href="importar-organizar-e-sumarizar-os-dados.html#passo-ajustar-os-dados"><i class="fa fa-check"></i><b>2.2</b> 2° passo: Ajustar os dados</a></li>
<li class="chapter" data-level="2.3" data-path="importar-organizar-e-sumarizar-os-dados.html"><a href="importar-organizar-e-sumarizar-os-dados.html#passo-sumarizar-os-dados-graficamente"><i class="fa fa-check"></i><b>2.3</b> 3° passo: Sumarizar os dados graficamente</a><ul>
<li class="chapter" data-level="2.3.1" data-path="importar-organizar-e-sumarizar-os-dados.html"><a href="importar-organizar-e-sumarizar-os-dados.html#histogramas"><i class="fa fa-check"></i><b>2.3.1</b> HISTOGRAMAS</a></li>
<li class="chapter" data-level="2.3.2" data-path="importar-organizar-e-sumarizar-os-dados.html"><a href="importar-organizar-e-sumarizar-os-dados.html#gráfico-de-barras"><i class="fa fa-check"></i><b>2.3.2</b> GRÁFICO DE BARRAS</a></li>
<li class="chapter" data-level="2.3.3" data-path="importar-organizar-e-sumarizar-os-dados.html"><a href="importar-organizar-e-sumarizar-os-dados.html#gráfico-de-linhas"><i class="fa fa-check"></i><b>2.3.3</b> GRÁFICO DE LINHAS</a></li>
<li class="chapter" data-level="2.3.4" data-path="importar-organizar-e-sumarizar-os-dados.html"><a href="importar-organizar-e-sumarizar-os-dados.html#boxplot"><i class="fa fa-check"></i><b>2.3.4</b> BOXPLOT</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="importar-organizar-e-sumarizar-os-dados.html"><a href="importar-organizar-e-sumarizar-os-dados.html#passo-sumarizar-os-dados-numericamente"><i class="fa fa-check"></i><b>2.4</b> 4° passo: Sumarizar os dados numericamente</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="qui-quadrado-χ.html"><a href="qui-quadrado-χ.html"><i class="fa fa-check"></i><b>3</b> Qui-quadrado (χ²)</a><ul>
<li class="chapter" data-level="3.1" data-path="qui-quadrado-χ.html"><a href="qui-quadrado-χ.html#χ-para-ajuste-de-frequências"><i class="fa fa-check"></i><b>3.1</b> χ² para ajuste de frequências</a></li>
<li class="chapter" data-level="3.2" data-path="qui-quadrado-χ.html"><a href="qui-quadrado-χ.html#χ-para-independência"><i class="fa fa-check"></i><b>3.2</b> χ² para independência</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="teste-t-.html"><a href="teste-t-.html"><i class="fa fa-check"></i><b>4</b> Teste-t.</a><ul>
<li class="chapter" data-level="4.1" data-path="teste-t-.html"><a href="teste-t-.html#teste-t-para-uma-amostra"><i class="fa fa-check"></i><b>4.1</b> Teste-t para uma amostra</a></li>
<li class="chapter" data-level="4.2" data-path="teste-t-.html"><a href="teste-t-.html#teste-t-para-duas-amostras"><i class="fa fa-check"></i><b>4.2</b> Teste-t para duas amostras</a></li>
<li class="chapter" data-level="4.3" data-path="teste-t-.html"><a href="teste-t-.html#teste-t-pareado"><i class="fa fa-check"></i><b>4.3</b> Teste-t pareado</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="final-words.html"><a href="final-words.html"><i class="fa fa-check"></i><b>5</b> Final Words</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introdução a análise de dados ambientais em R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="importar-organizar-e-sumarizar-os-dados" class="section level1">
<h1><span class="header-section-number">Capítulo 2</span> Importar, organizar e sumarizar os dados</h1>
<div id="passo-definir-o-ambiente-de-trabalho-e-importar-a-planilha-de-dados-para-o-r" class="section level2">
<h2><span class="header-section-number">2.1</span> 1° passo: Definir o ambiente de trabalho e importar a planilha de dados para o R</h2>
<p>Ao se trabalhar com R a primeira pergunta que nos vem a cabeça é: Como inserir meus dados neste ambiente de trabalho? A resposta é simples e também complexa. Pois depende do formato do arquivo de dados que está usando ( *.csv, *.xls, *.xlsx, *.txt entre outros) e para o mesmo formato existem inúmeras vias possíveis para se fazer isso. Não iremos especificar todas as vias, mas as mais comuns (*.csv e *.xlsx), utilizando os comandos básicos do R e também por meio da interface gráfica do RStudio.</p>
<p>Para importar a planilha é necessário definir o ambiente de trabalho no seu computador. Este ambiente é onde sua planilha e seus demais dados a serem trabalhados estão. Podemos realizar isso via linhas de comando ou pela própria interface do RStudio. Se realizado por linhas de comandos há diferença entre o sistema operacional (Windows, Linux ou macOS) que estiver utilizando.</p>
<div id="definir-ambiente-de-trabalho-via-linha-de-comando" class="section level3">
<h3><span class="header-section-number">2.1.1</span> Definir ambiente de trabalho via linha de comando</h3>
<p>Para o sistema operacional Windows utilizamos o seguinte comando: <span style="color: blue;">setwd(choose.dir(<em>path</em>))</span> e para Linux utilizamos <span style="color: blue;">setwd(<em>path</em>)</span>, onde <span style="color: blue;"><em>path</em></span> é o caminho do diretório escolhido.</p>
<p>Se no Windows utilizarmos apenas a linha de comando <span style="color: blue;">setwd(choose.dir())</span> sem especificar o caminho a seguinte janela irá aparecer (Figura <a href="importar-organizar-e-sumarizar-os-dados.html#fig:setwd">2.1</a>), a partir da qual iremos selecionar a pasta onde estão os arquivos que iremos trabalhar e salvar nosso <em>script</em>.</p>
<div class="figure" style="text-align: center"><span id="fig:setwd"></span>
<img src="docs/livroR-1.0_files/figures%20print/setwd.JPG" alt="Janela que será aberta ao executar o comando: setwd(choose.dir()), no sistema operacional Windows." width="60%" />
<p class="caption">
Figura 2.1: Janela que será aberta ao executar o comando: setwd(choose.dir()), no sistema operacional Windows.
</p>
</div>
<p>A função <span style="color: blue;"><em>setwd()</em></span> é responsável por selecionar o diretório a ser trabalhado. Após isso podemos importar a planilha com os dados que utilizaremos.</p>
<p>Como resultado desta etapa podemos verificar a guia <em>Files</em> (Figura <a href="#fig:guia-files"><strong>??</strong></a>), nela agora situa-se as pastas e arquivos da pasta que selecionamos e onde estará salvo nosso script quando o salvarmos.</p>
<p><strong>[INSERIR PRINT DA GUIA FILES APÓS A PASTA TER SIDO SELECIONADA]</strong></p>
</div>
<div id="definir-ambiente-de-trabalho-via-interface-gráfica" class="section level3">
<h3><span class="header-section-number">2.1.2</span> Definir ambiente de trabalho via interface gráfica</h3>
<p>Inumeras formas podem ser utilizadas para definir o ambiente de trabalho, apresentaremos 3. A primeira consiste em usar o atalho do teclado <span class="math inline">\((CTRL + SHIFT + H)\)</span> onde irá aparecer a janela abaixo (Figura <a href="#fig:ctrl-shift-h"><strong>??</strong></a>) e nela selecionaremos o ambiente de trabalho; a segunda via consiste em acessar a guia <em>Session</em> ir até a opção <em>Set Working Directory</em> e selecionar a opção <em>Choose Directory</em> (Figura <a href="#fig:mode-2"><strong>??</strong></a>) da mesma forma que a opção anterior a mesma janela irá aparecer (Figura <a href="#fig:ctrl-shift-h"><strong>??</strong></a>); por último podemos usar a guia <em>Files</em> onde podemos clicar nos 3 pontos “…” que aparecem no canto superior direito da guia e buscar o ambiente/pasta que iremos utilizar e a seguir na engrenagem (<em>More</em>) e selecionar a opção <em>Set as Working Directory</em> (Figura <a href="#fig:files-guia"><strong>??</strong></a>).</p>
<p><strong>[Inserir PRINT da janela ctrl shift h]</strong></p>
<p><strong>[Inserir PRINT da janela session]</strong></p>
<p><strong>[Inserir PRINT da janela files-guia]</strong></p>
</div>
<div id="importar-planilha-via-linha-de-comando" class="section level3">
<h3><span class="header-section-number">2.1.3</span> Importar planilha via linha de comando:</h3>
<p>Primeiramente construa a planilha a seguir (Figura <a href="#fig:planilha"><strong>??</strong></a>) no formato *.csv (usando vírgula como separador de colunas e ponto como separador decimal) e *.xlsx em um editor de planilhas, como excel, libreoffice calc ou outros e a salve com o nome de planilha.csv e planilha.xlsx no diretório que definiu previamente. A seguir faremos a importação desta planilha.</p>
<p><strong>[Inserir imagem da planilha csv]</strong></p>
<p><strong>[Inserir imagem da planilha xlsx]</strong></p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" data-line-number="1">dados &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="dt">file =</span> <span class="st">&quot;planilha.csv&quot;</span>, <span class="dt">header =</span> <span class="ot">TRUE</span>, <span class="dt">sep =</span> <span class="st">&quot;,&quot;</span>)</a></code></pre></div>
<p>O comando <span style="color: blue;"><em>read.csv()</em></span> importou a planilha que está no formato *.csv utilizando os argumentos: file - o qual indica o nome do arquivo a ser importado; header - o qual indica se as colunas da planilha tem nome e sep - o qual indica qual o caracter separador das colunas</p>
<p>O comando acima importou a planilha e o guardou em um objeto chamado dados que será o que nós utilizaremos de agora em diante sempre que quisermos acessar essa planilha no R.</p>
<p>Para importar arquivos que estão no formato *.xls ou *.xlsx é necessário a instalação de algum pacote<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a> que permita a realização desse processo. Um pacote que instalaremos aqui é o <span style="color: green;"><em>readxl</em></span>.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb2-1" data-line-number="1"><span class="co">## install.packages(&quot;readxl&quot;)</span></a>
<a class="sourceLine" id="cb2-2" data-line-number="2"><span class="kw">library</span>(readxl)</a></code></pre></div>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" data-line-number="1">dados &lt;-<span class="st"> </span><span class="kw">read_excel</span>(<span class="dt">path =</span> <span class="st">&quot;planilha.xlsx&quot;</span>, <span class="dt">col_names =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<p>O comando <span style="color: blue;"><em>read_excel()</em></span> é similar ao <span style="color: blue;"><em>read.csv()</em></span> embora seus argumentos sejam diferentes. O argumento path é similar ao file, o argumento col_names é similar ao header. Repare que não temos o argumento sep, pois em um arquivo excel as variáveis são salvas em colunas diferentes.</p>
<p><strong>[Inserir imagem do resultado de importação - o arquivo presente no environment]</strong></p>
</div>
<div id="importar-planilha-pela-via-interface-gráfica" class="section level3">
<h3><span class="header-section-number">2.1.4</span> Importar planilha pela via interface gráfica:</h3>
<p>Para importar a planilha com os dados via interface do RStudio devemos acessar a guia <em>Environment</em> e nesta acessar a opção <em>Import Dataset</em> a seguir temos várias opções a qual devemos escolher referente a extensão do arquivo que vamos importar, no nosso caso será a opção <em>From Excel</em> (Figura <a href="#fig:import-graf"><strong>??</strong></a>).</p>
<p>Neste momento uma janela irá abrir (Figura <a href="#fig:import-graf-2"><strong>??</strong></a>) e no canto superior direito haverá o nome <em>Browse</em> onde deveremos clicar e escolher o arquivo com o qual iremos trabalhar. Em <em>Import options</em> no canto inferior esquerdo havera algumas opções, a opção <em>name</em> deveremos renomear para dados, para coincidir com as vias que fizemos acima. As demais opções podemos deixar em branco. Repare que no canto inferior direito aparecerá o comando relativo ao processo de importação similar ao que fizemos no tópico anterior e, aparecerá também, um comando chamado <span style="color: blue;"><em>View()</em></span> que veremos mais adiante, para desabilita-lo basta desmarcar a caixa ao lado de mesmonome. Conclua o processo clicando em <em>import</em> no canto inferior direito.</p>
<p><strong>[Inserir imagem do processo de importação via interface gráfica]</strong>
<strong>[Inserir imagem do processo de importação via interface gráfica janela com o arquivo]</strong></p>
</div>
</div>
<div id="passo-ajustar-os-dados" class="section level2">
<h2><span class="header-section-number">2.2</span> 2° passo: Ajustar os dados</h2>
<p>Uma falha comum de muitos usuários iniciantes é passar para as análises antes de verificar se a planilha está organizada corretamente. Uma forma de previnir isso é conhecendo os seus dados e sabendo o que eles significam. Os dados, geralmente, podem ser: categóricos/qualitativos ou mensuráveis/quantitativos. Quando qualitativos temos de informar que eles consistem em fatores. Para isso vamos executar alguns comandos onde poderemos avaliar se no processo de importação as variáveis presentes na planilha de dados são reconhecidas como esperamos que seja.</p>
<p>Ao executarmos a função <span style="color: blue;"><em>str()</em></span> do arquivo dados podemos ver no console o seguinte resultado</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4-1" data-line-number="1"><span class="kw">str</span>(dados)</a></code></pre></div>
<pre><code>## tibble [40 × 4] (S3: tbl_df/tbl/data.frame)
##  $ ano        : num [1:40] 2020 2020 2020 2020 2020 2020 2020 2020 2020 2020 ...
##  $ local      : chr [1:40] &quot;Ambiente 1&quot; &quot;Ambiente 1&quot; &quot;Ambiente 1&quot; &quot;Ambiente 1&quot; ...
##  $ comprimento: num [1:40] 10 11 15 12 17 14 19 16 15 12 ...
##  $ peso       : num [1:40] 20 21 24 24 23 28 26 25 21 22 ...</code></pre>
<p>Seu resultado nos informa sobre o tipo de objeto que o arquivo é. Neste caso um objeto do tipo tibble ou data frame.</p>
<p>Também nos e mostrado as variáveis presentes (ano, local, comprimento e peso) e ao lado de cada variável nos é indicado o tipo de variável que ele considerou.</p>
<p>num = numerico, chr = character e há outras que não estão indicadas aqui, lógica, inteiro, fator entre outros.</p>
<p>Repare que a variável ano foi indicada como númerico. Variáveis consideradas númericas são aquelas as quais foram mensuradas. Ano não é uma variável possível de ser medida, porém devido ao seu registro ter sido em valores númericos foi assim que ela foi entendida. Portanto temos que transforma-la.</p>
<p>Pensando no que definimos acima com variáveis categóricas e mensuráveis. Ano e local podem ser classificados como variáveis categóricas. A todas as variáveis de nossas planilha consideradas categóricas temos que transformar para fator. Este processo pode ser feito da seguinte forma:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb6-1" data-line-number="1">dados<span class="op">$</span>ano &lt;-<span class="st"> </span><span class="kw">as.factor</span>(dados<span class="op">$</span>ano)</a>
<a class="sourceLine" id="cb6-2" data-line-number="2">dados<span class="op">$</span>local &lt;-<span class="st"> </span><span class="kw">as.factor</span>(dados<span class="op">$</span>local)</a></code></pre></div>
<p>Repare que neste processo inserimos o operador <strong>$</strong> (cifrão). Este é um operador importante em toda linguagem de programação e será bastante utilizado. Ele permite acessar alguma variável dentro de um dado objeto. Pensando no objeto “dados” (nossa planilha), ao colocarmos seu nome e em seguida o operador <strong>$</strong> podemos acessar as variáveis dentro dele.</p>
<p>Inserimos também a função <span style="color: blue;"><em>as.factor()</em></span> que é a responsável por criar uma variável a qual será considerada categórica.</p>
<p>O comando portanto é lido da seguinte forma:
1. “dados$ano &lt;-” indica que uma variável ano será criada dentro do objeto “dados”.
2. “as.factor(dados$ano)” indica que o objeto criado consistirá na variável ano que está no objeto dados porém considerando-a como factor.</p>
<p>Uma dúvida pode aparece aqui: É o que aconteceu com a variável ano que já existia dentro da planilha dados? Temos duas variáveis ano, agora?</p>
<p>A resposta é que quando criamos um objeto ou variável com o mesmo nome o anterior é substituído. Imagine o seguinte exemplo.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" data-line-number="1">idade &lt;-<span class="st"> </span><span class="dv">30</span></a></code></pre></div>
<p>Repare o objeto idade criado no environment.</p>
<p>Agora crie um segundo objeto com o mesmo nome e repare no enviroment.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb8-1" data-line-number="1">idade &lt;-<span class="st"> </span><span class="dv">40</span></a></code></pre></div>
<p>Reparou que ao criar um segundo objeto de mesmo nome que antes o primeiro foi apagado e substituído pelo segundo? Este é o mesmo processo que ocorreu quando realizamos a função que definiu ano e local como fatores.</p>
<p>Vamos observar novamente a função <span style="color: blue;"><em>str()</em></span> para verificar se ano e locais são fatores</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" data-line-number="1"><span class="kw">str</span>(dados)</a></code></pre></div>
<pre><code>## tibble [40 × 4] (S3: tbl_df/tbl/data.frame)
##  $ ano        : Factor w/ 2 levels &quot;2020&quot;,&quot;2021&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ local      : Factor w/ 2 levels &quot;Ambiente 1&quot;,&quot;Ambiente 2&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ comprimento: num [1:40] 10 11 15 12 17 14 19 16 15 12 ...
##  $ peso       : num [1:40] 20 21 24 24 23 28 26 25 21 22 ...</code></pre>
<p>Como pode verificar agora temos 2 variáveis como fatores e 2 númericas. Mais que isso, essa função nos indica ao lado dos fatores um “w/2 levels” que está nos dizendo que essa variável tem 2 niveis. De maneira similar as variáveis númericas indicam um colchetes com os seguintes valores [1:40] que significa que temos 40 valores/observações/linhas.</p>
<p>Observe a planilha dados no environment. Repare que ao lado do nome dados há escrito 40obs. of 4 variables. Isto indica que temos 40 observações e 4 variáveis.</p>
<p>Que tal agora observarmos nossa planilha?</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" data-line-number="1"><span class="kw">head</span>(dados)</a></code></pre></div>
<pre><code>## # A tibble: 6 x 4
##   ano   local      comprimento  peso
##   &lt;fct&gt; &lt;fct&gt;            &lt;dbl&gt; &lt;dbl&gt;
## 1 2020  Ambiente 1          10    20
## 2 2020  Ambiente 1          11    21
## 3 2020  Ambiente 1          15    24
## 4 2020  Ambiente 1          12    24
## 5 2020  Ambiente 1          17    23
## 6 2020  Ambiente 1          14    28</code></pre>
<p>A função <span style="color: blue;"><em>head()</em></span> reproduz, no painel do console as primeiras linhas de nossa planilha</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" data-line-number="1"><span class="kw">View</span>(dados)</a></code></pre></div>
<p>A função <span style="color: blue;"><em>View()</em></span> abre uma aba, ao lado de seu script mostrando todos dados.</p>
<p>Experimente agora só escrever dados e rodar, o que aparece? experimente clicar no nome dados, presente no environment. O que você observou?</p>
<p>Se no primeiro caso você observou a planilha aparecendo no console parabéns você está indo no caminho certo. Se no segundo momento você observou que ao clicar sobre o nome dados ele executou a mesma coisa que a função <span style="color: blue;"><em>View()</em></span> você está indo maravilhosamente bem. Continue assim!</p>
<p>Isto não é tudo, mas sim o necessário começarmos a sumarizar os dados de maneira eficiente.</p>
<p>Não se esqueça que antes de trabalharmos nossos dados temos que entender o que eles são e a que eles se referem. A análise de dados sem prévio conhecimento sobre o que eles significam pode levar a interpretações errôneas, caso as análises realizadas indiquem algum resultado, ou então a muita dor de cabeça se algum comando para uma dada análise não funcionar como esperado.</p>
<p>Portanto siga os passos precisamente, não pule etapas para que não haja lacunas em seu conhecimento e busque diversificar a fonte do seu conhecimento. Pois o R é uma linguagem de programação e que como demonstramos até o momento há muitas vias possíveis de escrita para um mesmo resultado e diferentes autores podem escrever de formas diferentes.</p>
</div>
<div id="passo-sumarizar-os-dados-graficamente" class="section level2">
<h2><span class="header-section-number">2.3</span> 3° passo: Sumarizar os dados graficamente</h2>
<p>Já importamos nossa planilha e já a ajustamos. Que tal começarmos a ver a “mágica” acontecer e graficarmos nossso dados.</p>
<p>Muitos gráficos podem ser realizados, mas lembre-se que há toda uma ciência sobre isso.</p>
<p>Pensando nos gráficos mais comuns e úteis para nosso dia-a-dia e que nos permitem sumarizar nossos dados temos os histogramas, gráficos de barras, linhas e boxplots. Vamos então começar com esses e com o objetivo inicial de sumarizar nossos dados.</p>
<div id="histogramas" class="section level3">
<h3><span class="header-section-number">2.3.1</span> HISTOGRAMAS</h3>
<p>A função <span style="color: blue;"><em>hist()</em></span> permite visualizar os valores da variável comprimento (Figura <a href="importar-organizar-e-sumarizar-os-dados.html#fig:comp-hist">2.2</a>).</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb14-1" data-line-number="1"><span class="kw">hist</span>(dados<span class="op">$</span>comprimento)</a></code></pre></div>
<div class="figure"><span id="fig:comp-hist"></span>
<img src="livroR-1.0_files/figure-html/comp-hist-1.png" alt="Comprimento dos organismos da planilha dados" width="672" />
<p class="caption">
Figura 2.2: Comprimento dos organismos da planilha dados
</p>
</div>
<p>Repare que um gráfico foi gerado na sua janela lateral, na guia plots.</p>
<p>Perceba também que voltamos a usar o operador <em>$</em> (cifrão).</p>
<p>Nosso gráfico não está aparentemente muito agradável e um pouco sem cor. Vamos inserir alguns argumentos estéticos que melhoram sua visualização e entender como ele sumariza nossos dados (Figura <a href="importar-organizar-e-sumarizar-os-dados.html#fig:comp-hist-col">2.3</a>).</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" data-line-number="1"><span class="kw">hist</span>(dados<span class="op">$</span>comprimento, </a>
<a class="sourceLine" id="cb15-2" data-line-number="2">     <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">10</span>), </a>
<a class="sourceLine" id="cb15-3" data-line-number="3">     <span class="dt">xlim =</span> <span class="kw">c</span>(<span class="dv">9</span>, <span class="dv">20</span>), </a>
<a class="sourceLine" id="cb15-4" data-line-number="4">     <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>,</a>
<a class="sourceLine" id="cb15-5" data-line-number="5">     <span class="dt">main =</span> <span class="st">&quot;Meu Histograma&quot;</span>,</a>
<a class="sourceLine" id="cb15-6" data-line-number="6">     <span class="dt">xlab =</span> <span class="st">&quot;Comprimento&quot;</span>,</a>
<a class="sourceLine" id="cb15-7" data-line-number="7">     <span class="dt">ylab =</span> <span class="st">&quot;Frequência absoluta&quot;</span>)</a></code></pre></div>
<div class="figure"><span id="fig:comp-hist-col"></span>
<img src="livroR-1.0_files/figure-html/comp-hist-col-1.png" alt="Comprimento dos organismos da planilha dados com barras coloridas" width="672" />
<p class="caption">
Figura 2.3: Comprimento dos organismos da planilha dados com barras coloridas
</p>
</div>
<p>Temos aqui nosso histograma com alguns argumentos que permitem melhorar sua visualização. Ele nos permite visualizar os dados da variável comprimento e sua frequência de ocorrência.</p>
<p>Podemos observar nele que o valor mínimo observado é 10 e que o máximo é 19 e que as frequências das diferentes classes de comprimento formadas, variam entre 0 e aproximadamente 9. Será que isto que observamos está correto. Vamos ver no tópico a seguir.</p>
<p>Ainda em relação ao histograma podemos ver na função <span style="color: blue;"><em>hist()</em></span> que utilizamos diversos argumentos como: xlim, ylim, col, main, xlab e ylab, além de uma função chamada <span style="color: blue;"><em>c()</em></span>. Verifique a tabela abaixo para detalhes de cada um desses argumentos e da função <span style="color: blue;"><em>c()</em></span>. OBS: Essa função <span style="color: blue;"><em>c()</em></span> é muito importante e será utilizada constantemente ao longo de seu trajeto no R.</p>
<p><strong>[INSERIR TABELA EXPLICANDO OS ARGUMENTOS E A FUNÇÃO CONCATENAR]</strong></p>
</div>
<div id="gráfico-de-barras" class="section level3">
<h3><span class="header-section-number">2.3.2</span> GRÁFICO DE BARRAS</h3>
<p>Se já chegamos até esse ponto vamos exercitar um pouco antes de plotar o gráfico de barras.</p>
<p>Acesse a seguinte planilha: abundância. Vamos inseri-la no R com o nome abundancia. repare que retirei o acento. Sempre que trabalharmos com linguagem de programação evite acentuações, espaços, cedilhas (ç) e atente a maiúsculas e minúsculas, pois isso pode interferir no seu código</p>
<p>Se estiver iniciando o R agora lembre-se de definir o ambiente de trabalho.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb16-1" data-line-number="1">abundancia &lt;-<span class="st"> </span><span class="kw">read_excel</span>(<span class="st">&quot;abundancia.xlsx&quot;</span>, <span class="dt">col_names =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<p>Repare que ela está no formato *.xlsx e apresenta as seguintes variáveis: mes e N. Onde N significa o número de indivíduos observado.</p>
<p>Vamos apenas conferir se está tudo certo com os dados usando a função <span style="color: blue;"><em>str()</em></span>.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb17-1" data-line-number="1"><span class="kw">str</span>(abundancia)</a></code></pre></div>
<pre><code>## tibble [12 × 3] (S3: tbl_df/tbl/data.frame)
##  $ mes   : num [1:12] 1 2 3 4 5 6 7 8 9 10 ...
##  $ N     : num [1:12] 100 70 50 30 35 40 60 90 110 150 ...
##  $ desvio: num [1:12] 10 12 11 8 8 14 11 9 12 15 ...</code></pre>
<p>Vamos converter a variável mês em factor.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb19-1" data-line-number="1">abundancia<span class="op">$</span>mes &lt;-<span class="st"> </span><span class="kw">as.factor</span>(abundancia<span class="op">$</span>mes)</a></code></pre></div>
<p>Repare que agora que sabemos os passos a realizar desde a importação dos arquivos tudo ficou muito mais fácil e fluído, e apenas realizamos três etapas, sendo uma delas apenas conferência.</p>
<p>Seguindo para o gráfico de barras (Figura <a href="importar-organizar-e-sumarizar-os-dados.html#fig:bar-abu">2.4</a>) a fim de mostrar o número de indivíduos ao longo dos meses temos que:</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb20-1" data-line-number="1"><span class="kw">barplot</span>(abundancia<span class="op">$</span>N)</a></code></pre></div>
<div class="figure"><span id="fig:bar-abu"></span>
<img src="livroR-1.0_files/figure-html/bar-abu-1.png" alt="Gráfico de barras com número de indivíduos da planilha abundância por mês" width="672" />
<p class="caption">
Figura 2.4: Gráfico de barras com número de indivíduos da planilha abundância por mês
</p>
</div>
<p>Assim como o histograma o simples uso da função sem argumentos gera um gráfico de dificil análise e esteticamente não muito agradavel.</p>
<p>Vamos portanto adicionar alguns argumentos já conhecidos e outros novos que permitirão a melhor análise do gráfico (Figura <a href="importar-organizar-e-sumarizar-os-dados.html#fig:bar-abu-col">2.5</a>).</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb21-1" data-line-number="1"><span class="kw">barplot</span>(abundancia<span class="op">$</span>N,</a>
<a class="sourceLine" id="cb21-2" data-line-number="2">        <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">200</span>),</a>
<a class="sourceLine" id="cb21-3" data-line-number="3">        <span class="dt">xlab =</span> <span class="st">&quot;Mês&quot;,</span></a>
<a class="sourceLine" id="cb21-4" data-line-number="4"><span class="st">        ylab = &quot;</span>Abundância<span class="st">&quot;,</span></a>
<a class="sourceLine" id="cb21-5" data-line-number="5"><span class="st">        names.arg = abundancia$mes,</span></a>
<a class="sourceLine" id="cb21-6" data-line-number="6"><span class="st">        col = &quot;</span>green<span class="st">&quot;)</span></a></code></pre></div>
<div class="figure"><span id="fig:bar-abu-col"></span>
<img src="livroR-1.0_files/figure-html/bar-abu-col-1.png" alt="Gráfico de barras com número de indivíduos da planilha abundância por mês, com barras coloridas" width="672" />
<p class="caption">
Figura 2.5: Gráfico de barras com número de indivíduos da planilha abundância por mês, com barras coloridas
</p>
</div>
<p>Podemos extrair desse gráfico que a abundância dos indivíduos variam ao longo dos meses com valores mínimos em torno de 50 indivíduos nos meses 4, 5 e 6 e valores máximos em torno de 200 indivíduos no mês 11.</p>
<p>Podemos ver que os argumentos utilizados permitiram referenciar as barras, ajustar o eixo y, adicionar cores e adicionar os nomes dos eixos. Para detalhes sobre os argumentos e funções utilizadas no <span style="color: blue;"><em>barplot()</em></span> (Tabela <a href="importar-organizar-e-sumarizar-os-dados.html#tab:tab-arg">2.1</a>).</p>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:tab-arg">Tabela 2.1: </span>Descrição dos argumentos utilizados para o gráfico de barras
</caption>
<thead>
<tr>
<th style="text-align:left;">
Argumentos
</th>
<th style="text-align:left;">
Características
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;">
ylim
</td>
<td style="text-align:left;width: 30em; ">
Refere-se aos limites do eixo y
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
xlab
</td>
<td style="text-align:left;width: 30em; ">
É usado para dar nome ao eixo x
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
ylab
</td>
<td style="text-align:left;width: 30em; ">
É usado para dar nome ao eixo y
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
names.arg
</td>
<td style="text-align:left;width: 30em; ">
É usado para definir o nome das categorias/barras representadas no eixo x, neste caso as categorias usadas estão vinculadas a coluna mes do objeto abundancia
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
col
</td>
<td style="text-align:left;width: 30em; ">
É usado para definir a cor das barras
</td>
</tr>
</tbody>
</table>
<p><strong>[INSERIR TABELA EXPLICANDO OS ARGUMENTOS E A FUNÇÃO CONCATENAR]</strong></p>
</div>
<div id="gráfico-de-linhas" class="section level3">
<h3><span class="header-section-number">2.3.3</span> GRÁFICO DE LINHAS</h3>
<p>Assim como o gráfico de barras podemos desejar fazer um gráfico de linhas para isso podemos utilizar a função <span style="color: blue;"><em>plot()</em></span> e continuar trabalhando com os dados de abundância por mês</p>
<p>Contudo para fazer um gráfico de linhas pelo comando básico do R (utilizando a função <span style="color: blue;"><em>plot()</em></span>) precisamos indicar que ambos os eixos apresentam variáveis númericas. Portanto teremos que modificar a variável mês de fator para numerica.</p>
<p>Porém não precisamos fazer isso em um comando separado podemos aplicar a função que converte uma variável em númerica dentro da função que plota o gráfico. Vamos visualizar como isso ocorre na prática (Figura <a href="importar-organizar-e-sumarizar-os-dados.html#fig:pon-graf">2.6</a>).</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb22-1" data-line-number="1"><span class="kw">plot</span>(<span class="dt">x =</span> <span class="kw">as.numeric</span>(abundancia<span class="op">$</span>mes), <span class="dt">y =</span> abundancia<span class="op">$</span>N)</a></code></pre></div>
<div class="figure"><span id="fig:pon-graf"></span>
<img src="livroR-1.0_files/figure-html/pon-graf-1.png" alt="Representação gráfica do número de indivíduos por mês em pontos" width="672" />
<p class="caption">
Figura 2.6: Representação gráfica do número de indivíduos por mês em pontos
</p>
</div>
<p>Pronto, na função acima aplicamos a função <span style="color: blue;"><em>plot()</em></span> indicando os argumentos x e y que definem quem estará no eixo x e quem estará no eixo y, e para a variável que estará no eixo x (variável mês) adicionamos a função <span style="color: blue;"><em>as.numeric()</em></span> a qual a converte em númerico apenas para a execução do plot.</p>
<p>Porém a função <span style="color: blue;"><em>plot()</em></span> não realizou um gráfico de linhas como esperado, pois para isso precisamos indica-lo por meio de argumentos. Como demonstraremos a seguir (Figura <a href="importar-organizar-e-sumarizar-os-dados.html#fig:lin-graf-col">2.7</a>).</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb23-1" data-line-number="1"><span class="kw">plot</span>(<span class="dt">x =</span> <span class="kw">as.numeric</span>(abundancia<span class="op">$</span>mes), </a>
<a class="sourceLine" id="cb23-2" data-line-number="2">     <span class="dt">y =</span> abundancia<span class="op">$</span>N, </a>
<a class="sourceLine" id="cb23-3" data-line-number="3">     <span class="dt">xlab =</span> <span class="st">&quot;Mês&quot;,</span></a>
<a class="sourceLine" id="cb23-4" data-line-number="4"><span class="st">     ylab = &quot;</span>Abundância<span class="st">&quot;,</span></a>
<a class="sourceLine" id="cb23-5" data-line-number="5"><span class="st">     main = &quot;</span>Meu gráfico de linha<span class="st">&quot;,</span></a>
<a class="sourceLine" id="cb23-6" data-line-number="6"><span class="st">     ylim = c(0, 200),</span></a>
<a class="sourceLine" id="cb23-7" data-line-number="7"><span class="st">     type = &quot;</span>l<span class="st">&quot;,</span></a>
<a class="sourceLine" id="cb23-8" data-line-number="8"><span class="st">     col = &quot;</span>green<span class="st">&quot;,</span></a>
<a class="sourceLine" id="cb23-9" data-line-number="9"><span class="st">     lwd = 2)</span></a></code></pre></div>
<div class="figure"><span id="fig:lin-graf-col"></span>
<img src="livroR-1.0_files/figure-html/lin-graf-col-1.png" alt="Representação gráfica do número de indivíduos por mês em um gráfico de linhas" width="672" />
<p class="caption">
Figura 2.7: Representação gráfica do número de indivíduos por mês em um gráfico de linhas
</p>
</div>
<p>Repare que um gráfico de linha foi plotado e o resultado deste indica o mesmo que o gráfico de barras que realizamos acima.</p>
<p>Alguns argumentos novos foram inseridos, os detalhes deles podem ser visualizados na tabela abaixo:</p>
<p><strong>[INSERIR TABELA EXPLICANDO OS ARGUMENTOS E A FUNÇÃO CONCATENAR]</strong></p>
</div>
<div id="boxplot" class="section level3">
<h3><span class="header-section-number">2.3.4</span> BOXPLOT</h3>
<p>Vamos voltar a nossa primeira planilha (dados) e executar um gráfico do tipo boxplot (Figura <a href="importar-organizar-e-sumarizar-os-dados.html#fig:box-graf">2.8</a>) e ver o que ele nos informa.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb24-1" data-line-number="1"><span class="kw">boxplot</span>(<span class="dt">formula =</span> dados<span class="op">$</span>comprimento <span class="op">~</span><span class="st"> </span>dados<span class="op">$</span>ano)</a></code></pre></div>
<div class="figure"><span id="fig:box-graf"></span>
<img src="livroR-1.0_files/figure-html/box-graf-1.png" alt="Gráfico tipo boxplot do comprimento por ano, da planilha dados" width="672" />
<p class="caption">
Figura 2.8: Gráfico tipo boxplot do comprimento por ano, da planilha dados
</p>
</div>
<p>Repare que a escrita para esse gráfico é ligeiramente diferente. Ele usa a função <span style="color: blue;"><em>boxplot()</em></span>, um argumento chamado formula onde nele inserimos a variável independente (variável do eixo X) e a variável dependente (variável do eixo Y). Entre ambas as variáveis é possível ver o caracter “~” (til). A forma de ler essa escrita é a seguinte: Realize um boxplot da variável comprimento da planilha dados em função da variável ano da planilha dados. A variável til é lida como (“em função de”)</p>
<p>Vamos adicionar alguns argumentos que permitem deixar o gráfico mais apresentável (Figura <a href="importar-organizar-e-sumarizar-os-dados.html#fig:box-graf-col">2.9</a>).</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb25-1" data-line-number="1"><span class="kw">boxplot</span>(<span class="dt">formula =</span> dados<span class="op">$</span>comprimento <span class="op">~</span><span class="st"> </span>dados<span class="op">$</span>ano,</a>
<a class="sourceLine" id="cb25-2" data-line-number="2">        <span class="dt">col =</span> <span class="kw">c</span>(<span class="st">&quot;blue&quot;</span>, <span class="st">&quot;green&quot;</span>),</a>
<a class="sourceLine" id="cb25-3" data-line-number="3">        <span class="dt">xlab =</span> <span class="st">&quot;Ano&quot;</span>,</a>
<a class="sourceLine" id="cb25-4" data-line-number="4">        <span class="dt">ylab =</span> <span class="st">&quot;Comprimento&quot;</span>,</a>
<a class="sourceLine" id="cb25-5" data-line-number="5">        <span class="dt">main =</span> <span class="st">&quot;Meu Boxplot&quot;</span>)</a></code></pre></div>
<div class="figure"><span id="fig:box-graf-col"></span>
<img src="livroR-1.0_files/figure-html/box-graf-col-1.png" alt="Gráfico tipo boxplot do comprimento por ano com cores por ano, da planilha dados" width="672" />
<p class="caption">
Figura 2.9: Gráfico tipo boxplot do comprimento por ano com cores por ano, da planilha dados
</p>
</div>
<p>Repare que não adicionamos nenhum argumento ou função diferente do que já fizemos anteriormente. Ou seja, uma vez conhecendo a função, os argumentos por vezes se repetem.</p>
<p>O boxplot porém nos fornece algumas informações extras em relação ao resumo dos dados. Podemos extrair dele dados como média, mediana (segundo quartil), primeiro e terceiro quartil, assim como máximos e mínimos da variável dependente.</p>
<p>As linhas de cada box (caixa) que se referem a cada um dos anos representam, em suas extremidades os valores máximos e mínimos de comprimento de cada ano. A topo e a base de cada “box” indicam o primeiro e terceiro quartil, respectivamente, do comprimento. A linha no interior da caixa indica a mediana (segundo quartil) e a metade do box (não indicada graficamente) indica a média.</p>
<p>Podemos por meio desse gráfico então ter uma ideia do que os dados indicam quanto as medidas de tendência central e algumas medidas de dispersão em relação as categorias definidas.</p>
</div>
</div>
<div id="passo-sumarizar-os-dados-numericamente" class="section level2">
<h2><span class="header-section-number">2.4</span> 4° passo: Sumarizar os dados numericamente</h2>
<p>Temos visto, até este ponto de maneira geral, como resumir os dados graficamente.</p>
<p>Porém muitas vezes precisamos demonstrar numericamente quais são os valores que resumem dos dados. Estes valores consistem nas medidas de tendência central e nas suas medidas de dispersão.</p>
<p>O R permite, de maneira simples, sumarizar os dados por meio da seguinte função.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb26-1" data-line-number="1"><span class="kw">summary</span>(dados)</a></code></pre></div>
<pre><code>##    ano            local     comprimento         peso      
##  2020:20   Ambiente 1:15   Min.   :10.00   Min.   :18.00  
##  2021:20   Ambiente 2:25   1st Qu.:12.00   1st Qu.:20.00  
##                            Median :14.00   Median :21.50  
##                            Mean   :13.97   Mean   :21.73  
##                            3rd Qu.:15.00   3rd Qu.:23.00  
##                            Max.   :19.00   Max.   :28.00</code></pre>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb28-1" data-line-number="1"><span class="kw">summary</span>(abundancia)</a></code></pre></div>
<pre><code>##       mes          N              desvio     
##  1      :1   Min.   : 30.00   Min.   : 8.00  
##  2      :1   1st Qu.: 47.50   1st Qu.: 9.75  
##  3      :1   Median : 80.00   Median :11.50  
##  4      :1   Mean   : 88.75   Mean   :11.75  
##  5      :1   3rd Qu.:120.00   3rd Qu.:14.00  
##  6      :1   Max.   :180.00   Max.   :17.00  
##  (Other):6</code></pre>
<p>Repare que <span style="color: blue;"><em>summary()</em></span> o R nos informou as variáveis presentes nestas planilhas e quando fator indicou quais são e quantos de cada existem e quando númerico nos retornou valores como média, mediana, mínimo, máximo, primeiro e terceiro quartis.</p>
<p>As medidas de tendência central mais conhecidas e aplicadas são média, mediana e moda.</p>
<p>Para obtenção da média precisamos somar todos os valores e dividir pela quantidade de valores ou no R podemos fazer isso de maneira mais simples por meio da função <span style="color: blue;"><em>mean()</em></span>:</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb30-1" data-line-number="1"><span class="kw">mean</span>(dados<span class="op">$</span>comprimento)</a></code></pre></div>
<pre><code>## [1] 13.975</code></pre>
<p>Como podemos verificar a média do comprimento na planilha dados é de 13.975.</p>
<p>De maneira similar podemos calcular a mediana, que consiste no valor central da distribuição de valores de uma dada variável. Podemos visualiza-la por meio da função <span style="color: blue;"><em>median()</em></span>.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb32-1" data-line-number="1"><span class="kw">median</span>(dados<span class="op">$</span>comprimento)</a></code></pre></div>
<pre><code>## [1] 14</code></pre>
<p>Como podemos verificar o valor que se encontra no meio da distribuição de valores da variável comprimento é 14.</p>
<p>As medidas de dispersão são utilizadas para demonstrar a variabilidade dos dados…[explicar mais]</p>
<p>Os limites inferior e superior de uma dada variável quantitativa são denominados mínimo e máximo e podem ser obtidos por meio das funções que calculam o mínimo e máximo. Apesar de seu resultado aparecer na função <span style="color: blue;"><em>summary()</em></span>, que aplicamos anteriormente, podemos obte-la separadamente para uma variável especifica. Vamos conferi-la com o conjunto de dados que utilizamos anteriormente.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb34-1" data-line-number="1"><span class="kw">min</span>(dados<span class="op">$</span>comprimento)</a></code></pre></div>
<pre><code>## [1] 10</code></pre>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb36-1" data-line-number="1"><span class="kw">max</span>(dados<span class="op">$</span>comprimento)</a></code></pre></div>
<pre><code>## [1] 19</code></pre>
<p>Uma outra forma de obter os valores máximo e mínimo é usando a função <span style="color: blue;"><em>range()</em></span>.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb38-1" data-line-number="1"><span class="kw">range</span>(dados<span class="op">$</span>comprimento)</a></code></pre></div>
<pre><code>## [1] 10 19</code></pre>
<p>Como puderam verificar utilizando a função <span style="color: blue;"><em>min()</em></span> e <span style="color: blue;"><em>max()</em></span> ou <span style="color: blue;"><em>range()</em></span> obtemos os valores mínimo e máximo da variável comprimento. Repare que usamos o operador cifrão (<strong>$</strong>) após o nome do conjunto de dados. Como você aprendeu anteriormente ele permite acessar as variáveis que estão dentro do objeto dados.</p>
<p>Com os valores mínimo e máximo podemos obter nossa primeira medida de dispersão dos dados. A amplitude que consiste na diferença entre os valores máximo e mínimo de nossa amostra. Está é a forma mais simples de verificar a dispersão de seus dados. Ela apresenta suas falhas, porém tem a vantagem de fornecer a distância na qual seus dados variam na mesma unidade em que eles estão.</p>
<p>A amplitude é utilizada para dados quantitativos, descrever a variabilidade de uma amostra, porém não para inferência estatística.</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb40-1" data-line-number="1"><span class="kw">max</span>(dados<span class="op">$</span>comprimento) <span class="op">-</span><span class="st"> </span><span class="kw">min</span>(dados<span class="op">$</span>comprimento)</a></code></pre></div>
<pre><code>## [1] 9</code></pre>
<p>Como podemos ver, ao calcular a diferença entre o máximo e mínimo da mesma variável obtemos a diferença entre elas e esse valor consiste na amplitude desta variável.</p>
<p>Uma outra forma de realizar esta mesma operação é utilizando a função <span style="color: blue;"><em>diff()</em></span> que calcula a diferença. Quando inserimos a função <span style="color: blue;"><em>range()</em></span> dentro da função <span style="color: blue;"><em>diff()</em></span> o R nos retorna o resultado da diferença dos valores obtidos pela função <span style="color: blue;"><em>range()</em></span>.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb42-1" data-line-number="1"><span class="kw">diff</span>(<span class="kw">range</span>(dados<span class="op">$</span>comprimento))</a></code></pre></div>
<pre><code>## [1] 9</code></pre>
<p>O desvio padrão. Esta é uma das medidas de variação mais importantes que iremos realizar. Ele mede a distância dos valores observados em relação a sua média.</p>
<p>Durante a coleta de dados em estudos ambientais, o que normalmente é extraído de informação é uma fração de um todo, ou seja, uma amostra de uma população. Portanto quando se deseja avaliar o desvio padrão, assim como outras medidas de variabilidade, devemos considerar se estamos avaliando uma amostra ou toda a população. Se uma amostra é considerada o nos referimos a ela como desvio padrão amostral e a representamos por (s) se toda a população é considerada nos referimos a ela como desvio padrão populacional e a representamos por (sigma).</p>
<p>Neste livro vamos abordar e considerar o desvio padrão como o desvio padrão amostral.</p>
<p>Para calcular o desvio padrão amostral utilizamos a seguinte formula abaixo:</p>
<p><strong>[INSERIR FORMULA]</strong></p>
<p>Podemos calcular o desvio padrão a partir de suas partes, considerando sua formula ou a partir de uma função pré-existente no R. Vamos conferir as duas formas.</p>
<p>Para facilitar o entendimento do código vamos começar criando os seguintes objetos:</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb44-1" data-line-number="1">comp &lt;-<span class="st"> </span>dados<span class="op">$</span>comprimento</a>
<a class="sourceLine" id="cb44-2" data-line-number="2">comp.media &lt;-<span class="st"> </span><span class="kw">mean</span>(dados<span class="op">$</span>comprimento)</a>
<a class="sourceLine" id="cb44-3" data-line-number="3">N &lt;-<span class="st"> </span><span class="kw">length</span>(dados<span class="op">$</span>comprimento)</a>
<a class="sourceLine" id="cb44-4" data-line-number="4"></a>
<a class="sourceLine" id="cb44-5" data-line-number="5">comp</a></code></pre></div>
<pre><code>##  [1] 10 11 15 12 17 14 19 16 15 12 14 15 12 12 14 13 12 11 14 14 13 12 11 15 12
## [26] 14 13 12 11 15 15 17 16 17 15 16 15 16 15 17</code></pre>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb46-1" data-line-number="1">comp.media</a></code></pre></div>
<pre><code>## [1] 13.975</code></pre>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb48-1" data-line-number="1">N</a></code></pre></div>
<pre><code>## [1] 40</code></pre>
<ul>
<li>“comp” contêm os dados da variável comprimento presente na planilha dados</li>
<li>“comp.media” contêm um dado que consiste na média da variável comprimento</li>
<li>“N” representa a quantidade de observações presentes na variável comprimento. Repare que aqui utilizamos uma nova função chamada <span style="color: blue;"><em>length()</em></span> a qual contabiliza o número de observações de objeto.</li>
</ul>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb50-1" data-line-number="1"><span class="kw">sqrt</span>((<span class="kw">sum</span>((comp <span class="op">-</span><span class="st"> </span>comp.media)<span class="op">^</span><span class="dv">2</span>)) <span class="op">/</span><span class="st"> </span>(N <span class="op">-</span><span class="st"> </span><span class="dv">1</span>))</a></code></pre></div>
<pre><code>## [1] 2.106005</code></pre>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb52-1" data-line-number="1"><span class="kw">sd</span>(dados<span class="op">$</span>comprimento)</a></code></pre></div>
<pre><code>## [1] 2.106005</code></pre>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb54-1" data-line-number="1"><span class="kw">sd</span>(comp)</a></code></pre></div>
<pre><code>## [1] 2.106005</code></pre>
<p>Destas três formas cabe explicarmos a primeira. Nela vamos entender como lemos uma função. O ideal é ler de dentro para fora. Como uma equação matemática. Mas não se assuste é mais fácil do que parece. Começamos a leitura da seguinte forma:</p>
<ol style="list-style-type: decimal">
<li>(comp - comp.media): Realize a diferença dos valores presentes em comp de sua média.</li>
<li>((comp - comp.media)^2): Eleve esses valores, obtidos da diferença, ao quadrado.</li>
<li>(sum((comp - comp.media)^2)): Soma todos os valores, obtidos pela diferença elevados ao quadrado.</li>
<li>(sum((comp - comp.media)^2)) / (N - 1): Divida a soma dos valores da diferença elevado ao quadrado pelo número de observações menos 1.</li>
<li>sqrt((sum((comp - comp.media)^2)) / (N - 1)): Extraia a raíz quadrada da divisão da soma dos valores da diferença elevado ao quadrado pelo número de observações menos 1.</li>
</ol>
<p>Repare que a leitura segue a ordem dos passos do cálculo que seria feito a mão usando a equação apresentada acima.</p>
<p>Mas caso não queira escrever a formula o R fornece a função <span style="color: blue;"><em>sd()</em></span> que pode ser aplicada a uma variável dentro de uma planilha de dados ou a um vetor que contenha um conjunto de observações do seu interesse.</p>
<p>Pronto, agora enetendemos como ler um código que apresenta funções dentro de funções e entendemos como realizar o desvio padrão de três formas distintas (existem diversas outras formas) no R. Agora você já pode escolher a que mais lhe agrada. Qual você prefere? Bem, essa é uma escolha sua.</p>
<p>Assim como o desvio padrão temos também a variância. A mais importante medida de variabilidade dos dados. Há todo um conjunto espécial de análise de dados voltado para ela. Mas como poderão ver, ela não difere muito do desvio padrão, apenas pelo fato de que consiste no seu valor elevado ao quadrado, no entanto a variância amostral é representada por s² enquanto que o desvio padrão é representado por s.</p>
<p>Partindo dessa ideia a variância é nada mais que estimar o desvio padrão e eleva-lo ao quadrado. Vamos observar o seu resultado utilizando sua formula e a função predefinida pelo R.</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb56-1" data-line-number="1">(<span class="kw">sum</span>((comp <span class="op">-</span><span class="st"> </span>comp.media)<span class="op">^</span><span class="dv">2</span>)) <span class="op">/</span><span class="st"> </span>(N <span class="op">-</span><span class="st"> </span><span class="dv">1</span>)</a></code></pre></div>
<pre><code>## [1] 4.435256</code></pre>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb58-1" data-line-number="1"><span class="kw">sd</span>(dados<span class="op">$</span>comprimento)<span class="op">^</span><span class="dv">2</span></a></code></pre></div>
<pre><code>## [1] 4.435256</code></pre>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb60-1" data-line-number="1"><span class="kw">var</span>(dados<span class="op">$</span>comprimento)</a></code></pre></div>
<pre><code>## [1] 4.435256</code></pre>
<p>Pronto aqui estão 3 maneiras de encontrar a variância de seus dados. A primeira é similar ao que realizamos anteriormente para o desvio padrão porém sem a raíz quadrada. A segunda consiste em elevar ao quadrado o resultado do desvio padrão e a terceira é aplicando a função <span style="color: blue;"><em>var()</em></span> a variável comprimento presente na planilha dados.</p>
<p>Difícil? Espero que não.</p>
<p>Mas vamos entender o significado do desvio padrão e variância. Pois ambos estão intimamente relacionados.</p>
<p>Como conversamos anteriormente as medidas de tendência central nos informam sobre a distância das observações de uma dada variável em relação a sua medida de tendência central (normalmente a média). Se somarmos a diferença das observações de uma dada variável de sua média obteremos o valor de 0 (tabela abaixo). Contudo se elevarmos cada diferença ao quadrado e dividirmos pela quantidade de observações menos 1 (subtrai-se 1 das observações porque estamos trabalhando com amostras) teremos a média das distâncias das observações ao quadrado (variância). Porém algumas vezes esse valor pode não ser fácil de interpretar e não reflete diretamente a unidade da variável mensurada. Com isso uma forma mais intuitiva utilizada para interpretar a dispersão dos dados em relação a sua média consiste no desvio padrão, pois como vimos este consiste na raiz quadrada da variância, ao fazermos isso nos obtemos a distância média das observações em relação a sua média na mesma unidade de medida em que se encontram.</p>
<p>O coeficiente de variação é outra medida importante e de fácil interpretação sobre a variabilidade dos dados. Este consiste em representar o desvio padrão em termos percentuais. Este é simples de calcular e intuitivo de interpretar.</p>
<p>Não há, até o momento, uma função no pacote básico do R que o calcule. Vamos calcular e ver o que ele quer dizer.</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb62-1" data-line-number="1"><span class="kw">sd</span>(dados<span class="op">$</span>comprimento)<span class="op">/</span><span class="kw">mean</span>(dados<span class="op">$</span>comprimento)<span class="op">*</span><span class="dv">100</span></a></code></pre></div>
<pre><code>## [1] 15.0698</code></pre>
<p>Pronto, calculamos o coeficiente de variação da variável comprimento. O desvio padrão de uma dada observação apresenta a mesma unidade de suas observações, correto? Então podemos dividi-lo pela média das próprias observações e multiplicar por 100 com isso temos que a variável comprimento tem uma variação em torno da média de ±15,07%.</p>
<p>Com isso verificamos as principais medidas de tendência central e dispersão. Mas fica uma questão, como incorpora-las aos gráficos para que assim possamos resumir os dados graficamente de maneira mais completa.</p>
<p>Vamos em frente! Vamos utilizar nossa planilha dados e verificar a média do comprimento e do peso por ano e por ambiente e incorporar em cada um dos gráficos seus respectivos desvios padrões.</p>
<p>Neste caso vamos primeiro precisar organizar os dados que queremos plotar. Como desejamos plotar a média do comprimento por ano e ambiente, vamos primeiro construir passo a passo uma tabela que apresente 4 colunas a primeira com o ano, a segunda com ambiente, a terceira com a média do comprimento e a última com o desvio padrão.</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb64-1" data-line-number="1">dados<span class="fl">.2</span> &lt;-<span class="st"> </span><span class="kw">split</span>(<span class="dt">x =</span> dados, <span class="dt">f =</span> dados<span class="op">$</span>ano)</a>
<a class="sourceLine" id="cb64-2" data-line-number="2"></a>
<a class="sourceLine" id="cb64-3" data-line-number="3">ano<span class="fl">.2020</span> &lt;-<span class="st"> </span>dados<span class="fl">.2</span><span class="op">$</span><span class="st">`</span><span class="dt">2020</span><span class="st">`</span></a>
<a class="sourceLine" id="cb64-4" data-line-number="4">ano<span class="fl">.2021</span> &lt;-<span class="st"> </span>dados<span class="fl">.2</span><span class="op">$</span><span class="st">`</span><span class="dt">2021</span><span class="st">`</span></a>
<a class="sourceLine" id="cb64-5" data-line-number="5"></a>
<a class="sourceLine" id="cb64-6" data-line-number="6">ano.<span class="fl">2020.</span>local &lt;-<span class="st"> </span><span class="kw">split</span>(<span class="dt">x =</span> ano<span class="fl">.2020</span>, <span class="dt">f =</span> ano<span class="fl">.2020</span><span class="op">$</span>local)</a>
<a class="sourceLine" id="cb64-7" data-line-number="7">ano.<span class="fl">2021.</span>local &lt;-<span class="st"> </span><span class="kw">split</span>(<span class="dt">x =</span> ano<span class="fl">.2021</span>, <span class="dt">f =</span> ano<span class="fl">.2021</span><span class="op">$</span>local)</a>
<a class="sourceLine" id="cb64-8" data-line-number="8"></a>
<a class="sourceLine" id="cb64-9" data-line-number="9">ano.<span class="fl">2020.</span>local<span class="fl">.1</span> &lt;-<span class="st"> </span>ano.<span class="fl">2020.</span>local<span class="op">$</span><span class="st">`</span><span class="dt">Ambiente 1</span><span class="st">`</span></a>
<a class="sourceLine" id="cb64-10" data-line-number="10">ano.<span class="fl">2020.</span>local<span class="fl">.2</span> &lt;-<span class="st"> </span>ano.<span class="fl">2020.</span>local<span class="op">$</span><span class="st">`</span><span class="dt">Ambiente 2</span><span class="st">`</span></a>
<a class="sourceLine" id="cb64-11" data-line-number="11"></a>
<a class="sourceLine" id="cb64-12" data-line-number="12">ano.<span class="fl">2021.</span>local<span class="fl">.1</span> &lt;-<span class="st"> </span>ano.<span class="fl">2021.</span>local<span class="op">$</span><span class="st">`</span><span class="dt">Ambiente 1</span><span class="st">`</span></a>
<a class="sourceLine" id="cb64-13" data-line-number="13">ano.<span class="fl">2021.</span>local<span class="fl">.2</span> &lt;-<span class="st"> </span>ano.<span class="fl">2021.</span>local<span class="op">$</span><span class="st">`</span><span class="dt">Ambiente 2</span><span class="st">`</span></a></code></pre></div>
<p>Pronto! Dividimos os nosso dados de acordo com os fatores que desejamos. Agora vamos obter as métricas média e desvio padrão.</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb65-1" data-line-number="1">ano.<span class="fl">2020.</span>local.<span class="fl">1.</span>comp.media &lt;-<span class="st"> </span><span class="kw">mean</span>(ano.<span class="fl">2020.</span>local<span class="fl">.1</span><span class="op">$</span>comprimento)</a>
<a class="sourceLine" id="cb65-2" data-line-number="2">ano.<span class="fl">2020.</span>local.<span class="fl">1.</span>comp.dp &lt;-<span class="st"> </span><span class="kw">sd</span>(ano.<span class="fl">2020.</span>local<span class="fl">.1</span><span class="op">$</span>comprimento)</a>
<a class="sourceLine" id="cb65-3" data-line-number="3"></a>
<a class="sourceLine" id="cb65-4" data-line-number="4">ano.<span class="fl">2020.</span>local.<span class="fl">2.</span>comp.media &lt;-<span class="st"> </span><span class="kw">mean</span>(ano.<span class="fl">2020.</span>local<span class="fl">.2</span><span class="op">$</span>comprimento)</a>
<a class="sourceLine" id="cb65-5" data-line-number="5">ano.<span class="fl">2020.</span>local.<span class="fl">2.</span>comp.dp &lt;-<span class="st"> </span><span class="kw">sd</span>(ano.<span class="fl">2020.</span>local<span class="fl">.2</span><span class="op">$</span>comprimento)</a>
<a class="sourceLine" id="cb65-6" data-line-number="6"></a>
<a class="sourceLine" id="cb65-7" data-line-number="7">ano.<span class="fl">2021.</span>local.<span class="fl">1.</span>comp.media &lt;-<span class="st"> </span><span class="kw">mean</span>(ano.<span class="fl">2021.</span>local<span class="fl">.1</span><span class="op">$</span>comprimento)</a>
<a class="sourceLine" id="cb65-8" data-line-number="8">ano.<span class="fl">2021.</span>local.<span class="fl">1.</span>comp.dp &lt;-<span class="st"> </span><span class="kw">sd</span>(ano.<span class="fl">2021.</span>local<span class="fl">.1</span><span class="op">$</span>comprimento)</a>
<a class="sourceLine" id="cb65-9" data-line-number="9"></a>
<a class="sourceLine" id="cb65-10" data-line-number="10">ano.<span class="fl">2021.</span>local.<span class="fl">2.</span>comp.media &lt;-<span class="st"> </span><span class="kw">mean</span>(ano.<span class="fl">2021.</span>local<span class="fl">.2</span><span class="op">$</span>comprimento)</a>
<a class="sourceLine" id="cb65-11" data-line-number="11">ano.<span class="fl">2021.</span>local.<span class="fl">2.</span>comp.dp &lt;-<span class="st"> </span><span class="kw">sd</span>(ano.<span class="fl">2021.</span>local<span class="fl">.2</span><span class="op">$</span>comprimento)</a></code></pre></div>
<p>Pronto! Média e desvio padrão do comprimento calculado para cada ano e local. Agora vamos unir esses resultados em uma data frame</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb66-1" data-line-number="1">dados.media &lt;-<span class="st"> </span><span class="kw">c</span>(ano.<span class="fl">2020.</span>local.<span class="fl">1.</span>comp.media,</a>
<a class="sourceLine" id="cb66-2" data-line-number="2">                 ano.<span class="fl">2020.</span>local.<span class="fl">2.</span>comp.media,</a>
<a class="sourceLine" id="cb66-3" data-line-number="3">                 ano.<span class="fl">2021.</span>local.<span class="fl">1.</span>comp.media,</a>
<a class="sourceLine" id="cb66-4" data-line-number="4">                 ano.<span class="fl">2021.</span>local.<span class="fl">2.</span>comp.media)</a>
<a class="sourceLine" id="cb66-5" data-line-number="5"></a>
<a class="sourceLine" id="cb66-6" data-line-number="6">dados.dp &lt;-<span class="st"> </span><span class="kw">c</span>(ano.<span class="fl">2020.</span>local.<span class="fl">1.</span>comp.dp,</a>
<a class="sourceLine" id="cb66-7" data-line-number="7">              ano.<span class="fl">2020.</span>local.<span class="fl">2.</span>comp.dp,</a>
<a class="sourceLine" id="cb66-8" data-line-number="8">              ano.<span class="fl">2021.</span>local.<span class="fl">1.</span>comp.dp,</a>
<a class="sourceLine" id="cb66-9" data-line-number="9">              ano.<span class="fl">2021.</span>local.<span class="fl">2.</span>comp.dp)</a></code></pre></div>
<p>Vamos criar as variáveis categoricas e ano e local para adicionar a esse dados</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb67-1" data-line-number="1">ano &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;2020&quot;</span>, <span class="st">&quot;2020&quot;</span>, <span class="st">&quot;2021&quot;</span>, <span class="st">&quot;2021&quot;</span>)</a>
<a class="sourceLine" id="cb67-2" data-line-number="2">local &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Ambiente 1&quot;</span>, <span class="st">&quot;Ambiente 2&quot;</span>, <span class="st">&quot;Ambiente 1&quot;</span>, <span class="st">&quot;Ambiente 2&quot;</span>)</a>
<a class="sourceLine" id="cb67-3" data-line-number="3"></a>
<a class="sourceLine" id="cb67-4" data-line-number="4">dados<span class="fl">.3</span> &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(<span class="kw">cbind</span>(ano, local, dados.media, dados.dp))</a>
<a class="sourceLine" id="cb67-5" data-line-number="5"><span class="kw">str</span>(dados<span class="fl">.3</span>)</a></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    4 obs. of  4 variables:
##  $ ano        : chr  &quot;2020&quot; &quot;2020&quot; &quot;2021&quot; &quot;2021&quot;
##  $ local      : chr  &quot;Ambiente 1&quot; &quot;Ambiente 2&quot; &quot;Ambiente 1&quot; &quot;Ambiente 2&quot;
##  $ dados.media: chr  &quot;14.1&quot; &quot;13.1&quot; &quot;13&quot; &quot;14.8&quot;
##  $ dados.dp   : chr  &quot;2.84604989415154&quot; &quot;1.28668393770792&quot; &quot;1.58113883008419&quot; &quot;1.93464651625488&quot;</code></pre>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb69-1" data-line-number="1">dados<span class="fl">.3</span><span class="op">$</span>ano &lt;-<span class="st"> </span><span class="kw">as.factor</span>(dados<span class="fl">.3</span><span class="op">$</span>ano)</a>
<a class="sourceLine" id="cb69-2" data-line-number="2">dados<span class="fl">.3</span><span class="op">$</span>local &lt;-<span class="st"> </span><span class="kw">as.factor</span>(dados<span class="fl">.3</span><span class="op">$</span>local)</a>
<a class="sourceLine" id="cb69-3" data-line-number="3">dados<span class="fl">.3</span><span class="op">$</span>dados.media &lt;-<span class="st"> </span><span class="kw">as.numeric</span>(dados<span class="fl">.3</span><span class="op">$</span>dados.media)</a>
<a class="sourceLine" id="cb69-4" data-line-number="4">dados<span class="fl">.3</span><span class="op">$</span>dados.dp &lt;-<span class="st"> </span><span class="kw">as.numeric</span>(dados<span class="fl">.3</span><span class="op">$</span>dados.dp)</a></code></pre></div>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb70-1" data-line-number="1">dados<span class="fl">.3</span></a></code></pre></div>
<pre><code>##    ano      local dados.media dados.dp
## 1 2020 Ambiente 1        14.1 2.846050
## 2 2020 Ambiente 2        13.1 1.286684
## 3 2021 Ambiente 1        13.0 1.581139
## 4 2021 Ambiente 2        14.8 1.934647</code></pre>
<p>Repare que durante todo este processo utilizamos três funções que não haviamos utilizado antes. As funções <span style="color: blue;"><em>split()</em></span> que divide a planilha de acordo com as categorias presentes na variável que definimos, <span style="color: blue;"><em>as.data.frame()</em></span> que faz com que um conjunto de objetos sejam convertidos em data frame e <span style="color: blue;"><em>cbind()</em></span> o qual une objetos como colunas. Essas funções também serão comumente utilizadas durante seus passos iniciais no R.</p>
<p>Pronto! depois de alguns passos conseguimos construir nossa nova tabela com os dados resumidos.</p>
<p>É um processo longo porém necessário para se acostumar com o ambiente de trabalho e a linguagem que o R usa. Há caminhos mais rápidos e tão eficientes quanto. Que se tornam uteis quando lidamos com muitas categorias dentro de uma variável. Contudo para isso é necessário a instalação de algum pacote (Há vários pacotes que apresentam funções que realizam este processo). Vamos utilizar um exemplo começando pela instalação do pacote chamado <span style="color: green;"><em>Rmisc</em></span>.</p>
<p>O comando abaixo realiza a instalação desse pacote. Conforme já fizemos com o pacote readxl</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb72-1" data-line-number="1"><span class="co">## install.packages(&quot;Rmisc&quot;)</span></a></code></pre></div>
<p>Após instalado vamos carrega-lo pelo comando a seguir. Conforme já fizemos com o pacote readxl</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb73-1" data-line-number="1"><span class="kw">library</span>(Rmisc)</a></code></pre></div>
<p>Agora vamos conhecer a função <span style="color: blue;"><em>summarySE()</em></span> deste pacote o qual realiza os passos que fizemos acima e ainda apresenta outros resultados. Mas iremos focar na média e desvio padrão.</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb74-1" data-line-number="1">resultado &lt;-<span class="st"> </span><span class="kw">summarySE</span>(<span class="dt">data =</span> dados, </a>
<a class="sourceLine" id="cb74-2" data-line-number="2">                       <span class="dt">measurevar =</span> <span class="st">&quot;comprimento&quot;</span>, </a>
<a class="sourceLine" id="cb74-3" data-line-number="3">                       <span class="dt">groupvars =</span> <span class="kw">c</span>(<span class="st">&quot;ano&quot;</span>, <span class="st">&quot;local&quot;</span>))</a>
<a class="sourceLine" id="cb74-4" data-line-number="4"></a>
<a class="sourceLine" id="cb74-5" data-line-number="5">resultado</a></code></pre></div>
<pre><code>##    ano      local  N comprimento       sd        se        ci
## 1 2020 Ambiente 1 10        14.1 2.846050 0.9000000 2.0359414
## 2 2020 Ambiente 2 10        13.1 1.286684 0.4068852 0.9204382
## 3 2021 Ambiente 1  5        13.0 1.581139 0.7071068 1.9632432
## 4 2021 Ambiente 2 15        14.8 1.934647 0.4995236 1.0713715</code></pre>
<p>Repare que a função <span style="color: blue;"><em>summarySE()</em></span> apresenta, basicamente, 3 argumentos, “data” que pede que se insira a planilha a ser utilizada, “measurevar” o qual pede a variável quantitativa que será sumarizada e “groupvars” o qual pede as variáveis categoricas segundo as quais a variável mensurável será agrupada. Observe também que para esta função as variáveis devem ser colocadas entre aspas.</p>
<p>Pronto com a função acima realizamos os mesmos passos que antes e guardamos o resultado dentro de um objeto chamado resultado. Repare que essa função nos resumiu os dados de comprimento de acordo com as duas variáveis categóricas que indicamos: ano e local. Em seu resumo ele nos forneceu, na seguinte ordem, a coluna ano, local, N (número de observações), comprimento (média do comprimento), sd (desvio padrão), se (erro padrão), ci (intervalo de confiança de 95%).</p>
<p>Agora vamos usar o objeto resultado para desenvolver o gráfico de barras com o erro padrão (Figura <a href="importar-organizar-e-sumarizar-os-dados.html#fig:bar-ep">2.10</a>). Mas lembre-se o objeto dados.3 também pode ser utilizado.</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb76-1" data-line-number="1">grafico &lt;-<span class="st"> </span><span class="kw">barplot</span>(<span class="dt">formula =</span> comprimento <span class="op">~</span><span class="st"> </span>ano <span class="op">+</span><span class="st"> </span>local,</a>
<a class="sourceLine" id="cb76-2" data-line-number="2">                   <span class="dt">data =</span> resultado,</a>
<a class="sourceLine" id="cb76-3" data-line-number="3">                   <span class="dt">beside =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb76-4" data-line-number="4">                   <span class="dt">col =</span> <span class="kw">c</span>(<span class="st">&quot;red&quot;</span>, <span class="st">&quot;blue&quot;</span>),</a>
<a class="sourceLine" id="cb76-5" data-line-number="5">                   <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">30</span>),</a>
<a class="sourceLine" id="cb76-6" data-line-number="6">                   <span class="dt">ylab =</span> <span class="st">&quot;Comprimento médio (cm)&quot;</span>,</a>
<a class="sourceLine" id="cb76-7" data-line-number="7">                   <span class="dt">legend.text =</span> <span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb76-8" data-line-number="8"></a>
<a class="sourceLine" id="cb76-9" data-line-number="9"><span class="kw">arrows</span>(<span class="dt">x0 =</span> grafico,</a>
<a class="sourceLine" id="cb76-10" data-line-number="10">       <span class="dt">y0 =</span> resultado<span class="op">$</span>comprimento <span class="op">+</span><span class="st"> </span>resultado<span class="op">$</span>sd,</a>
<a class="sourceLine" id="cb76-11" data-line-number="11">       <span class="dt">y1 =</span> resultado<span class="op">$</span>comprimento <span class="op">-</span><span class="st"> </span>resultado<span class="op">$</span>sd,</a>
<a class="sourceLine" id="cb76-12" data-line-number="12">       <span class="dt">code =</span> <span class="dv">3</span>,</a>
<a class="sourceLine" id="cb76-13" data-line-number="13">       <span class="dt">angle =</span> <span class="dv">90</span>,</a>
<a class="sourceLine" id="cb76-14" data-line-number="14">       <span class="dt">length =</span> <span class="fl">0.05</span>)</a></code></pre></div>
<div class="figure"><span id="fig:bar-ep"></span>
<img src="livroR-1.0_files/figure-html/bar-ep-1.png" alt="Gráfico de barras com erro padrão do comprimento por ano e local, da planilha resultado (derivada da planilha dados)" width="672" />
<p class="caption">
Figura 2.10: Gráfico de barras com erro padrão do comprimento por ano e local, da planilha resultado (derivada da planilha dados)
</p>
</div>
<p>Note que nesta função <span style="color: blue;"><em>barplot()</em></span> utilizamos algumas mudanças em relação ao que fizemos anteriormente, como os argumentos “formula” o qual indica a variável resposta em função das variáveis categóricas o qual será plotado (Caso altere a ordem ano + local para local + ano a ordem do gráfico também será alterado. Teste você mesmo, veja o acontece). Neste caso como temos mais de uma variável categórica adicionamos um argumento novo chamado “legend.text” o qual adiciona uma legenda ao gráfico.</p>
<p>Para adicionar os desvios no gráfico de barras precisamos criar um objeto que armazena o gráfico, por isso adicionamos a função <span style="color: blue;"><em>barplot()</em></span> a um objeto denominado grafico.</p>
<p>Agora que construimos o gráfico, a função <span style="color: blue;"><em>arrows()</em></span> é responsável por adicionar as barras de desvios no gráfico. Ela apresenta alguns argumentos diferentes do que já vimos em outros gráficos. “x0” indica o objeto onde o gráfico foi armazenado; “y0” e “y1” são escritos como uma operação matemática onde devemos incluir o valor da média + e - a coluna onde está a variável referente ao desvio; “code” determina o tipo de seta que será plotada; “angle” é o ângulo da haste da barra até a ponta; “length” é o comprimento das bordas da barra.</p>
<p>Terminamos de construir e entender os componentes do nosso primeiro gráfico com suas barras de erro.</p>
<p>O entendimento principal para construção desse gráfico consiste em entender como organizar os dados a serem graficados. Ao se usar a função <span style="color: blue;"><em>barplot()</em></span> para construção do gráfico de barras com os desvios, devemos ter uma ou mais colunas com as categorias, outra com os valores que desejamos e outra com os valores dos desvios.</p>
<p>Vamos realizar um segundo tipo de gráfico onde temos apenas uma variável categórica e seus respectivos desvios. Para isso utilizaremos nosso conjunto de dados abundancia (lembre-se que mês é uma variável categórica e deve ser identificada como fator) (Figura <a href="importar-organizar-e-sumarizar-os-dados.html#fig:bar-ep-abu">2.11</a>).</p>
<p>Neste conjunto de dados não precisamos reorganizar os dados pois eles já se encontram organizados e já temos os valores dos desvios.</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb77-1" data-line-number="1">grafico &lt;-<span class="st"> </span><span class="kw">barplot</span>(abundancia<span class="op">$</span>N,</a>
<a class="sourceLine" id="cb77-2" data-line-number="2">                   <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">200</span>),</a>
<a class="sourceLine" id="cb77-3" data-line-number="3">                   <span class="dt">xlab =</span> <span class="st">&quot;Mês&quot;,</span></a>
<a class="sourceLine" id="cb77-4" data-line-number="4"><span class="st">                   ylab = &quot;</span>Abundância<span class="st">&quot;,</span></a>
<a class="sourceLine" id="cb77-5" data-line-number="5"><span class="st">                   names.arg = abundancia$mes,</span></a>
<a class="sourceLine" id="cb77-6" data-line-number="6"><span class="st">                   col = &quot;</span>green<span class="st">&quot;)</span></a>
<a class="sourceLine" id="cb77-7" data-line-number="7"></a>
<a class="sourceLine" id="cb77-8" data-line-number="8"><span class="st">arrows(x0 = grafico,</span></a>
<a class="sourceLine" id="cb77-9" data-line-number="9"><span class="st">       y0 = abundancia$N + abundancia$desvio,</span></a>
<a class="sourceLine" id="cb77-10" data-line-number="10"><span class="st">       y1 = abundancia$N - abundancia$desvio,</span></a>
<a class="sourceLine" id="cb77-11" data-line-number="11"><span class="st">       code = 3,</span></a>
<a class="sourceLine" id="cb77-12" data-line-number="12"><span class="st">       angle = 90,</span></a>
<a class="sourceLine" id="cb77-13" data-line-number="13"><span class="st">       length = 0.05)</span></a></code></pre></div>
<div class="figure"><span id="fig:bar-ep-abu"></span>
<img src="livroR-1.0_files/figure-html/bar-ep-abu-1.png" alt="Gráfico de barras com erro padrão da abundância por mês da planilha abundância" width="672" />
<p class="caption">
Figura 2.11: Gráfico de barras com erro padrão da abundância por mês da planilha abundância
</p>
</div>
<p>Repare que é quase a mesma coisa que fizemos antes. A única diferença é que guardamos o gráfico gerado em um objeto chamado “grafico”.</p>
<p>Pronto, gráfico realizado.</p>
<p>Durante nosso percurso neste livro realizaremos muito mais gráficos aliados as análises estatísticas básicas mais comumente utilizadas. Não se assuste com a quantidade de etapas e funções e argumentos e nomes, eles irão se repetir tantas e tantas vezes daqui em diante que você não esquecerá. O aprendizado do R é exponencial e ele lhe permitirá entender como nunca o universo da análise de dados adequando-o para seu campo de atuação.</p>
<p><strong>Resumo das etapas até o presente momento:</strong>
<strong>importar planinha &gt;&gt; conferir as variáveis &gt;&gt; sumarizar numericamente os dados &gt;&gt; sumarizar graficamente os dados</strong></p>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="2">
<li id="fn2"><p>Tudo que é realizado no R é por meio de comandos, esses comandos são compostos de funções, podemos reconhece-las pois, obrigatoriamente, logo após um nome que representa uma função há um parênteses e cada função apresenta argumentos, o qual depois dele há o sinal de igual (=). As funções estão dentro de pacotes/bibliotecas. Ou seja, cada biblioteca apresenta diversas funções e cada função diversos argumentos. O R, quando instalado, traz consigo alguns pacotes, mas estes pacotes não apresentam uma função que permite carregar arquivos *.xls ou *.xlsx. Portanto para que isso seja possível devemos instalar, neste caso o pacote readxl. Para instalação de pacotes podemos usar a função conhecida por install.packages(“nome do pacote”).<a href="importar-organizar-e-sumarizar-os-dados.html#fnref2" class="footnote-back">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="r.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="qui-quadrado-χ.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["livroR-1.0.pdf", "livroR-1.0.docx"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
