<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 4 Teste-t. | Introdução a análise de dados em R: Uma abordagem ambiental e ecológica</title>
  <meta name="description" content="Este é o primeiro livro da série de livros: Análise de dados em R" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 4 Teste-t. | Introdução a análise de dados em R: Uma abordagem ambiental e ecológica" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Este é o primeiro livro da série de livros: Análise de dados em R" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 4 Teste-t. | Introdução a análise de dados em R: Uma abordagem ambiental e ecológica" />
  
  <meta name="twitter:description" content="Este é o primeiro livro da série de livros: Análise de dados em R" />
  

<meta name="author" content="Wilson Souza &amp; Thiago Couto" />


<meta name="date" content="2020-12-01" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="qui-quadrado-chi.html"/>
<link rel="next" href="final-words.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Introdução a análise de dados ambientais em R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Prefácio</a></li>
<li class="chapter" data-level="" data-path="sobre-os-autores.html"><a href="sobre-os-autores.html"><i class="fa fa-check"></i>Sobre os autores</a></li>
<li class="chapter" data-level="1" data-path="r.html"><a href="r.html"><i class="fa fa-check"></i><b>1</b> R</a><ul>
<li class="chapter" data-level="1.1" data-path="r.html"><a href="r.html#o-que-é"><i class="fa fa-check"></i><b>1.1</b> O que é?</a></li>
<li class="chapter" data-level="1.2" data-path="r.html"><a href="r.html#porque-usá-lo-para-análise-de-dados"><i class="fa fa-check"></i><b>1.2</b> Porque usá-lo para análise de dados?</a></li>
<li class="chapter" data-level="1.3" data-path="r.html"><a href="r.html#o-rstudio"><i class="fa fa-check"></i><b>1.3</b> O RStudio</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="importar-organizar-e-sumarizar-os-dados.html"><a href="importar-organizar-e-sumarizar-os-dados.html"><i class="fa fa-check"></i><b>2</b> Importar, organizar e sumarizar os dados</a><ul>
<li class="chapter" data-level="2.1" data-path="importar-organizar-e-sumarizar-os-dados.html"><a href="importar-organizar-e-sumarizar-os-dados.html#passo-definir-o-ambiente-de-trabalho-e-importar-a-planilha-de-dados-para-o-r"><i class="fa fa-check"></i><b>2.1</b> 1° passo: Definir o ambiente de trabalho e importar a planilha de dados para o R</a><ul>
<li class="chapter" data-level="2.1.1" data-path="importar-organizar-e-sumarizar-os-dados.html"><a href="importar-organizar-e-sumarizar-os-dados.html#definir-ambiente-de-trabalho-via-linha-de-comando"><i class="fa fa-check"></i><b>2.1.1</b> Definir ambiente de trabalho via linha de comando</a></li>
<li class="chapter" data-level="2.1.2" data-path="importar-organizar-e-sumarizar-os-dados.html"><a href="importar-organizar-e-sumarizar-os-dados.html#definir-ambiente-de-trabalho-via-interface-gráfica"><i class="fa fa-check"></i><b>2.1.2</b> Definir ambiente de trabalho via interface gráfica</a></li>
<li class="chapter" data-level="2.1.3" data-path="importar-organizar-e-sumarizar-os-dados.html"><a href="importar-organizar-e-sumarizar-os-dados.html#importar-planilha-via-linha-de-comando"><i class="fa fa-check"></i><b>2.1.3</b> Importar planilha via linha de comando:</a></li>
<li class="chapter" data-level="2.1.4" data-path="importar-organizar-e-sumarizar-os-dados.html"><a href="importar-organizar-e-sumarizar-os-dados.html#importar-planilha-via-interface-gráfica"><i class="fa fa-check"></i><b>2.1.4</b> Importar planilha via interface gráfica:</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="importar-organizar-e-sumarizar-os-dados.html"><a href="importar-organizar-e-sumarizar-os-dados.html#passo-ajustar-os-dados"><i class="fa fa-check"></i><b>2.2</b> 2° passo: Ajustar os dados</a></li>
<li class="chapter" data-level="2.3" data-path="importar-organizar-e-sumarizar-os-dados.html"><a href="importar-organizar-e-sumarizar-os-dados.html#passo-sumarizar-os-dados-graficamente"><i class="fa fa-check"></i><b>2.3</b> 3° passo: Sumarizar os dados graficamente</a><ul>
<li class="chapter" data-level="2.3.1" data-path="importar-organizar-e-sumarizar-os-dados.html"><a href="importar-organizar-e-sumarizar-os-dados.html#histograma"><i class="fa fa-check"></i><b>2.3.1</b> Histograma</a></li>
<li class="chapter" data-level="2.3.2" data-path="importar-organizar-e-sumarizar-os-dados.html"><a href="importar-organizar-e-sumarizar-os-dados.html#gráfico-de-barras"><i class="fa fa-check"></i><b>2.3.2</b> GRÁFICO DE BARRAS</a></li>
<li class="chapter" data-level="2.3.3" data-path="importar-organizar-e-sumarizar-os-dados.html"><a href="importar-organizar-e-sumarizar-os-dados.html#gráfico-de-linhas"><i class="fa fa-check"></i><b>2.3.3</b> GRÁFICO DE LINHAS</a></li>
<li class="chapter" data-level="2.3.4" data-path="importar-organizar-e-sumarizar-os-dados.html"><a href="importar-organizar-e-sumarizar-os-dados.html#boxplot"><i class="fa fa-check"></i><b>2.3.4</b> BOXPLOT</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="importar-organizar-e-sumarizar-os-dados.html"><a href="importar-organizar-e-sumarizar-os-dados.html#passo-sumarizar-os-dados-numericamente"><i class="fa fa-check"></i><b>2.4</b> 4° passo: Sumarizar os dados numericamente</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="qui-quadrado-chi.html"><a href="qui-quadrado-chi.html"><i class="fa fa-check"></i><b>3</b> Qui-quadrado (<span class="math inline">\(\chi\)</span>²)</a><ul>
<li class="chapter" data-level="3.1" data-path="qui-quadrado-chi.html"><a href="qui-quadrado-chi.html#chi-para-ajuste-de-frequências"><i class="fa fa-check"></i><b>3.1</b> <span class="math inline">\(\chi\)</span>² para ajuste de frequências</a></li>
<li class="chapter" data-level="3.2" data-path="qui-quadrado-chi.html"><a href="qui-quadrado-chi.html#chi-para-independência"><i class="fa fa-check"></i><b>3.2</b> <span class="math inline">\(\chi\)</span>² para independência</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="teste-t-.html"><a href="teste-t-.html"><i class="fa fa-check"></i><b>4</b> Teste-t.</a><ul>
<li class="chapter" data-level="4.1" data-path="teste-t-.html"><a href="teste-t-.html#teste-t-para-uma-amostra"><i class="fa fa-check"></i><b>4.1</b> Teste-t para uma amostra</a></li>
<li class="chapter" data-level="4.2" data-path="teste-t-.html"><a href="teste-t-.html#teste-t-para-duas-amostras"><i class="fa fa-check"></i><b>4.2</b> Teste-t para duas amostras</a></li>
<li class="chapter" data-level="4.3" data-path="teste-t-.html"><a href="teste-t-.html#teste-t-pareado"><i class="fa fa-check"></i><b>4.3</b> Teste-t pareado</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="final-words.html"><a href="final-words.html"><i class="fa fa-check"></i><b>5</b> Final Words</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introdução a análise de dados em R: Uma abordagem ambiental e ecológica</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="teste-t." class="section level1">
<h1><span class="header-section-number">Capítulo 4</span> Teste-t.</h1>
<p>Ao iniciarmos nossos estudos geralmente estamos interessados em saber se alguma característica da população que coletamos e analisamos é similar a uma outra população. Podemos abordar essa ideia por diversos caminhos porém vamos iniciar nossas análises em R através do teste-t para uma amostra e a discussão sobre hipótese nula, caudalidade e nível de confiança. A partir de então seguiremos para o teste-t com duas amostras e o teste-t pareado.</p>
<div id="teste-t-para-uma-amostra" class="section level2">
<h2><span class="header-section-number">4.1</span> Teste-t para uma amostra</h2>
<p>Conduzimos esse teste quando objetivamos verificar se a média de uma dada variável é similar a um valor esperado. Ao falarmos de média percebemos que a variável com a qual estamos lidando é do tipo númerica ou inteiro (a diferença entre ambas consiste na presença de casas decimais), ou seja, quantitativo. Ao compararmos a média de nossa variável a um valor previamente estipulado 2 hipóteses são construídas, a hipótese nula (H0) e a hipótese alternativa (HA). H0 diz que a média de nossa variável é similar ao valor previamente estipulado, enquanto que HA diz que a média de nossa variável é diferente do valor previamente estipulado.</p>
<p>Matematicamente podemos obter o resultado do teste-t pela seguinte fórmula: <span class="math inline">\(t_s=(x-mi)/(s/sqrt(n))\)</span>. Onde, x: média da amostra, mi: média teórica esperada, s: desvio padrão da amostra, n: tamanho da amostra.</p>
<p>Vamos verificar como conduzir esse teste no R por meio de exemplos utilizando valores fictícios.</p>
<p>Imagine o seguinte exemplo: 100 camarões foram coletados em um estuário. Suas medidas em relação ao tamanho foram tomadas e deseja-se saber se o seu tamanho médio é similar ou não ao tamanho médio (25,80 mm) da mesma espécie observada em outro estuario.</p>
<p>A partir do exemplo acima podemos definir nossas hipóteses, onde.</p>
<p>H0: média observada igual à média esperada;</p>
<p>HA: média observada diferente da média esperada;</p>
<p>Vamos começar gerando os dados relativos ao tamanho observado dos camarões que coletamos</p>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb127-1" data-line-number="1"><span class="kw">set.seed</span>(<span class="dv">1234</span>)</a>
<a class="sourceLine" id="cb127-2" data-line-number="2">tamanho.camarao &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dt">n =</span> <span class="dv">100</span>) <span class="op">+</span><span class="st"> </span><span class="kw">runif</span>(<span class="dt">n =</span> <span class="dv">100</span>, <span class="dt">min =</span> <span class="dv">17</span>, <span class="dt">max =</span> <span class="dv">33</span>)</a></code></pre></div>
<p>A função <em>set.seed()</em> define os números aleatórios que serão gerados. Dessa forma, quando aplicado essa função associada a um número comum, no caso “1234”, os números gerados aqui serão os mesmos em qualquer lugar.</p>
<p>A nossa segunda linha de comando utiliza a função <em>rnorm()</em> o qual gera números aleatórios considerando uma distribuição normal e soma esses valores gerados a uma distribuição uniforme gerada pela função <em>runif()</em>. A estas funções adicionamos argumentos que definem a quantidade de números gerados (argumento “n”), o valor mínimo que pode ser gerado (argumento “min”) e o valor máximo que pode ser gerado (argumento “max”). E guardamos o resultado obtido em um objeto chamado tamanho.camarao. Repare que o nome do objeto não apresenta espaços ou acentos, que pode gerar problemas e/ou dificuldades na condução das análises.</p>
<p>Vamos verificar o resultado. Basta digitarmos o nome do objeto.</p>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb128-1" data-line-number="1">tamanho.camarao</a></code></pre></div>
<pre><code>##   [1] 26.36501 25.73118 23.16434 26.93999 25.85006 29.22289 21.34791 22.92014
##   [9] 19.70599 31.88009 25.58378 20.48762 19.18464 29.19344 27.02799 31.80449
##  [17] 26.70808 27.30077 23.83039 33.02083 23.89138 17.01159 20.68980 22.81711
##  [25] 18.44307 23.54454 30.40893 21.37080 25.12759 23.97507 30.85514 25.59575
##  [33] 17.99771 29.42112 24.44470 19.22824 26.81323 20.57450 24.53800 32.36946
##  [41] 25.23524 19.84181 19.61879 27.74526 31.68906 23.66401 28.26906 24.93702
##  [49] 31.93121 29.25393 23.70445 25.96390 20.11329 20.45772 17.87934 26.57236
##  [57] 22.84551 16.27916 28.03817 24.16301 31.17074 20.02190 26.56155 20.62508
##  [65] 18.92214 20.38837 27.83197 18.62320 19.12094 29.29845 22.72270 28.68786
##  [73] 22.64878 30.43969 19.48136 24.94834 28.74896 24.99252 21.52521 22.19714
##  [81] 22.72903 23.69804 30.32393 29.37573 29.65554 22.18997 24.85922 21.19787
##  [89] 27.94906 28.93757 27.42930 23.87127 33.93523 21.89126 26.24338 29.48277
##  [97] 26.96407 19.72505 28.14750 24.06552</code></pre>
<p>Vamos observar as métricas e gráficos, conforme já fizemos nos capítulos anteriores, mas relativos ao objeto criado.</p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb130-1" data-line-number="1"><span class="kw">mean</span>(tamanho.camarao)</a></code></pre></div>
<pre><code>## [1] 24.86218</code></pre>
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb132-1" data-line-number="1"><span class="kw">min</span>(tamanho.camarao)</a></code></pre></div>
<pre><code>## [1] 16.27916</code></pre>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb134-1" data-line-number="1"><span class="kw">max</span>(tamanho.camarao)</a></code></pre></div>
<pre><code>## [1] 33.93523</code></pre>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb136-1" data-line-number="1"><span class="kw">length</span>(tamanho.camarao)</a></code></pre></div>
<pre><code>## [1] 100</code></pre>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb138-1" data-line-number="1"><span class="kw">hist</span>(tamanho.camarao)</a></code></pre></div>
<div class="figure"><span id="fig:hist-tam-cam"></span>
<img src="livroR-1.0_files/figure-html/hist-tam-cam-1.png" alt="Histograma dos valores do objeto relativo ao tamanho dos camarões" width="672" />
<p class="caption">
Figura 4.1: Histograma dos valores do objeto relativo ao tamanho dos camarões
</p>
</div>
<p>Como podemos ver os valores mínimo e máximo são similares ao que definimos e o número de elementos é o mesmo. Graficamente podemos ver que a distribuição é normal, pois como vimos utilizamos uma função que cria uma distribuição normal com limites definidos pela função <em>runif()</em>. Além disso vemos que há uma maior frequência dos valores em torno de 25 (Figura <a href="teste-t-.html#fig:hist-tam-cam">4.1</a>).</p>
<p>Vamos verificar, agora se esse valor que geramos (obtivemos de tamanho do camarão) são similares ao observado em outra localidade, por meio do teste-t para uma amostra.</p>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb139-1" data-line-number="1">esperado =<span class="st"> </span><span class="fl">25.80</span></a>
<a class="sourceLine" id="cb139-2" data-line-number="2"><span class="kw">t.test</span>(<span class="dt">x =</span> tamanho.camarao, <span class="dt">mu =</span> esperado)</a></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  tamanho.camarao
## t = -2.2432, df = 99, p-value = 0.02711
## alternative hypothesis: true mean is not equal to 25.8
## 95 percent confidence interval:
##  24.03263 25.69173
## sample estimates:
## mean of x 
##  24.86218</code></pre>
<p>Dois comandos foram executados, no primeiro criamos um objeto, denominado “esperado”, que guarda o valor referente ao tamanho de camarão observado em outro estuário (25,80 mm). O segundo comando que realizamos refere-se a função do teste-t no qual inserimos 2 argumentos. O primeiro argumento (x) refere-se ao nosso objeto que contem os dados referentes ao tamanho que coletamos e o segundo argumento (mu) refere-se ao objeto que contem a média do tamanho obtido em outro estuário.</p>
<p>Conforme podemos visualizar no resultado temos 9 linhas. A primeira linha nos diz qual teste está sendo conduzido, neste caso é (“One Sample t-test” ou teste-t par auma amostra), a segunda linha nos retorna o conjunto de dados que utilizamos, a terceira linha nos retorna o valor do teste t (t = -2,2432) o grau de liberdade (df = 99) e o valor de probabilidade associado ao teste (p-value = 0,02711), a quarta linha nos retorna qual é nossa hipótese alternativa, caso a aceitemos (a qual nos diz que: a média dos nossos dados não é igual à 25,8), a quinta e sexta linhas nos fornece o intervalo de confiança de 95% dos nossos dados (24,03263 e 25,69173) e da sétima a nona linha refere-se a informação relativa a média dos nossos dados (24,86218).</p>
<p>Em resumo, podemos inferir que a média dos nossos dados é diferente do valor esperado pois o p-value foi menor que 0,05. Além disso podemos dizer que a média do tamanho dos camarões que coletamos (24,86 mm) é estatisticamente menor do que a média presente no outro estuário (25,80 mm). De outra forma podemos dizer que se rejeitarmos H0 cometeremos um erro de 1,5% (p-value em percentual), ou seja, 1,5% de estarmos cometendo o erro tipo 1 (rejeitar a H0 quando ela é verdadeira), como 1,5% é menor que 5%, temos subsídio para afirmar que a média obtida (24,86 mm) é diferente da média esperada (25,80 mm) (98,5% de certeza).</p>
<p>Ok, verificamos e entendemos como conduzir a análise. Mas há um conceito estatístico importante na análise do teste-t, a caudalidade. No exemplo anterior nós trabalhamos com as hipóteses de que a média de um conjunto de dados é igual (H0) ou diferente (HA) da média esperada. O que implica em dizer que a média que observamos pode ser maior ou menor do que o esperado. Contudo em algumas instâncias podemos querer verificar se a média do nosso conjunto de dados é maior ou igual ou menor ou igual a média esperada e não diferente. Desta diferença na construção da hipótese que emerge o conceito da caudalidade. No exemplo anterior foi testado a hipótese bicaudal que é tido como padrão (“default”) na função do R que executamos.</p>
<p>A diferença entre realizar o teste-t bicaudal ou unicaudal depende da pergunta feita previamente e dos dados coletados. Então antes de realizar este teste mantenha-se atento a hipótese que se deseja testar.</p>
<p>Agora imagine o seguinte exemplo: Em um costão rochoso foi observado ao longo do dia “1” 100 estrelas do mar em diferentes alturas, em relação a baixamar. Essas alturas foram quantificadas (valores serão construídos abaixo). Sabe-se que no dia anterior “0” a altura média das estrelas no mesmo costão foi de 0,90 m. Sabe-se também que o dia anterior (dia 0) foi mais frio e que dias mais frios implicam em maiores alturas. A partir dessas informações e quais são as hipóteses testadas e o resultado do teste-t.</p>
<p>H0: A média da altura das estrelas do mar no costão no dia “1” é menor ou igual ao dia “0”</p>
<p>HA: A média da altura das estrelas do mar no costão no dia “1” é maior que a do dia “0”</p>
<p>Matematicamente podemos escrever da seguinte forma:</p>
<p>H0: μ ≤ 0,90</p>
<p>HA: μ &gt; 0,90</p>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb141-1" data-line-number="1"><span class="kw">set.seed</span>(<span class="dv">1234</span>)</a>
<a class="sourceLine" id="cb141-2" data-line-number="2">estrelas &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dt">n =</span> <span class="dv">100</span>, <span class="dt">sd =</span> <span class="fl">0.02</span>) <span class="op">+</span><span class="st"> </span><span class="kw">runif</span>(<span class="dt">n =</span> <span class="dv">100</span>, <span class="dt">min =</span> <span class="fl">0.4</span>, <span class="dt">max =</span> <span class="fl">1.3</span>)</a></code></pre></div>
<p>Observe que geramos os dados de maneira similar ao que fizemos no exemplo anterior (inserindo os valores das alturas das estrelas em um objeto chamado estrelas), a diferença é que inserimos um argumento na função <em>rnorm()</em> que corresponde ao desvio padrão (de 0,02) dos dados normais que estamos gerando.</p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb142-1" data-line-number="1"><span class="kw">mean</span>(estrelas)</a></code></pre></div>
<pre><code>## [1] 0.8479302</code></pre>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb144-1" data-line-number="1"><span class="kw">min</span>(estrelas)</a></code></pre></div>
<pre><code>## [1] 0.387487</code></pre>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb146-1" data-line-number="1"><span class="kw">max</span>(estrelas)</a></code></pre></div>
<pre><code>## [1] 1.290766</code></pre>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb148-1" data-line-number="1"><span class="kw">length</span>(estrelas)</a></code></pre></div>
<pre><code>## [1] 100</code></pre>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb150-1" data-line-number="1"><span class="kw">hist</span>(estrelas)</a></code></pre></div>
<div class="figure"><span id="fig:estrelas-hist"></span>
<img src="livroR-1.0_files/figure-html/estrelas-hist-1.png" alt="Histograma dos valores relativos a altura das estrelas do mar no costão rochoso" width="672" />
<p class="caption">
Figura 4.2: Histograma dos valores relativos a altura das estrelas do mar no costão rochoso
</p>
</div>
<p>Conforme também fizemos anteriormente calculamos algumas métricas para entender os dados e um histograma básico (Figura <a href="teste-t-.html#fig:estrelas-hist">4.2</a>) para visualizar a forma dos dados que representam a altura que as estrelas se encontram no ambiente.</p>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb151-1" data-line-number="1">dia<span class="fl">.0</span> =<span class="st"> </span><span class="fl">0.90</span></a>
<a class="sourceLine" id="cb151-2" data-line-number="2"><span class="kw">t.test</span>(<span class="dt">x =</span> estrelas, <span class="dt">mu =</span> dia<span class="fl">.0</span>, <span class="dt">alternative =</span> <span class="st">&quot;greater&quot;</span>)</a></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  estrelas
## t = -2.2073, df = 99, p-value = 0.9852
## alternative hypothesis: true mean is greater than 0.9
## 95 percent confidence interval:
##  0.8087617       Inf
## sample estimates:
## mean of x 
## 0.8479302</code></pre>
<p>Agora construímos um objeto chamado “dia.0” que nos retorna o valor médio encontrado para altura das estrelas do mar no costão no dia 0 e seguimos com o teste-t onde avaliamos se os dados que obtivemos do dia 1 são menores ou iguais ao dia 0, por meio do argumento “alternative” definido-o como “greater”. Este argumento novo que incluímos pode ser definido de 3 formas: “two-sided” que é o padrão (“default”), “greater” ou “less”. O argumento “alternative” seguirá o sinal da hipótese alternativa que foi construída para o teste.</p>
<p>Com isso podemos avaliar o resultado que é similar ao que vimos anteriormente com poucas mudanças. A primeira linha (One Sample t-test) informa sobre o teste realizado. A segunda linha indica o nome do conjunto de dados que inserimos. A terceira linha nos dá o valor do teste-t (t = -2,2073), do grau de liberdade (df = 99) e da probabilidade associada ao teste (p-value = 0.9852). A quarta linha indica a hipótese alternativa, caso seja aceita (o que não é o caso), que é verdade que a média dos nossos dados são maiores que 0,90 m. A quinta e sexta linha indicam o intervalo de confiança de 95% dos nossos dados (0,8087617 e inf). A sétima, oitava e nona linha referem-se a média dos dados.</p>
<p>Como podemos notar pelo p-value do nosso resultado este demonstra que não temos informação o suficiente para rejeitar nossa hipótese nula (H0). Portanto a média dos nossos dados é menor ou igual a 0,90.</p>
<p>Outro conceito importante de qualquer teste inferencial (ex. teste-t) é o nível de confiança. Até o presente momento consideramos o nível de confiança de 95%. Se quisermos altera-lo no teste-t devemos adicionar o argumento “conf.level” em proporção (0-1). A sua alteração implica na alteração da zona de rejeição da hipótese nula. Se aumentarmos o seu valor fica mais dificil rejeitarmos a hipótese nula e se diminuirmos o seu valor fica mais fácil rejeitar a hipótese nula. Vejamos outro exemplo.</p>
<p>Imagine o seguinte exemplo: Um pesquisador avaliou o tamanho de cracas incrustados no casco de uma embarcação. Objetivando saber se o tamanho médio de cracas difere do teórico esperado (20 mm) um teste-t bicaudal foi aplicado a um nível de confiança de 95% e 99%.</p>
<p>Vamos descrever as hipóteses e realizar a análise para ambos os níveis de confiança.</p>
<p>Neste caso temos as seguintes hipóteses:</p>
<p>H0: O tamanho médio observado é similar ao teórico</p>
<p>HA: O tamanho médio observado difere do teórico</p>
<p>Conforme já realizado anteriormente vamos gerar os dados e explora-los com algumas métricas estatśticas e gráficas de maneira similar ao que fizemos no exemplo anterior.</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb153-1" data-line-number="1"><span class="kw">set.seed</span>(<span class="dv">1234</span>)</a>
<a class="sourceLine" id="cb153-2" data-line-number="2">cracas &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dt">n =</span> <span class="dv">100</span>, <span class="dt">sd =</span> <span class="fl">1.9</span>) <span class="op">+</span><span class="st"> </span><span class="kw">runif</span>(<span class="dt">n =</span> <span class="dv">100</span>, <span class="dt">min =</span> <span class="dv">5</span>, <span class="dt">max =</span> <span class="dv">25</span>)</a>
<a class="sourceLine" id="cb153-3" data-line-number="3"></a>
<a class="sourceLine" id="cb153-4" data-line-number="4"><span class="kw">mean</span>(cracas)</a></code></pre></div>
<pre><code>## [1] 14.72583</code></pre>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb155-1" data-line-number="1"><span class="kw">min</span>(cracas)</a></code></pre></div>
<pre><code>## [1] 3.596275</code></pre>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb157-1" data-line-number="1"><span class="kw">max</span>(cracas)</a></code></pre></div>
<pre><code>## [1] 27.27792</code></pre>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb159-1" data-line-number="1"><span class="kw">length</span>(cracas)</a></code></pre></div>
<pre><code>## [1] 100</code></pre>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb161-1" data-line-number="1"><span class="kw">hist</span>(cracas)</a></code></pre></div>
<div class="figure"><span id="fig:craca-hist"></span>
<img src="livroR-1.0_files/figure-html/craca-hist-1.png" alt="Histograma dos valores relativos ao tambanho das cracas incrustantes" width="672" />
<p class="caption">
Figura 4.3: Histograma dos valores relativos ao tambanho das cracas incrustantes
</p>
</div>
<p>Agora que visualizamos as métricas e graficamos os dados (Figura <a href="teste-t-.html#fig:craca-hist">4.3</a>), sigamos com a condução da análise.</p>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb162-1" data-line-number="1">teorico &lt;-<span class="st"> </span><span class="fl">13.5</span></a>
<a class="sourceLine" id="cb162-2" data-line-number="2"><span class="kw">t.test</span>(<span class="dt">x =</span> cracas, <span class="dt">mu =</span> teorico, <span class="dt">conf.level =</span> <span class="fl">0.95</span>)</a></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  cracas
## t = 2.3113, df = 99, p-value = 0.02289
## alternative hypothesis: true mean is not equal to 13.5
## 95 percent confidence interval:
##  13.67349 15.77817
## sample estimates:
## mean of x 
##  14.72583</code></pre>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb164-1" data-line-number="1"><span class="kw">t.test</span>(<span class="dt">x =</span> cracas, <span class="dt">mu =</span> teorico, <span class="dt">conf.level =</span> <span class="fl">0.99</span>)</a></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  cracas
## t = 2.3113, df = 99, p-value = 0.02289
## alternative hypothesis: true mean is not equal to 13.5
## 99 percent confidence interval:
##  13.33290 16.11876
## sample estimates:
## mean of x 
##  14.72583</code></pre>
<p>Como podem ver ambos os resultados (com diferentes níveis de confiança) retornam o mesmo valor do teste-t e do “p-value”. E neste ponto precisamos ir com calma para evitar erro de interpretação do resultado e entender estatisticamente o que está acontencendo.</p>
<p>Quando representamos o nível de confiança (representado pelo argumento “conf.level”) por um valor probabilístico de 0,95 ou 0,99 estamos dizendo que o nível de significância é 0,05 e 0,01, respectivamente. Quando olhamos para o resultado do p-value, temos que levar em consideração o nível de significância (que consiste em: 1 - nível de confiança).</p>
<p>Vejamos o nosso resultado.</p>
<p>No primeiro caso (“conf.level = 0.95”) temos p-value = 0.02289, como este valor é menor que 0,05 (nosso nível de significância), isso quer dizer que a média teórica está fora do intervalo de confiança dos dados, portanto rejeitamos a hipótese nula.</p>
<p>No segundo caso (“conf.level = 0.99”) temos o mesmo “p-value”, contudo este valor é maior que nosso nível de significância (0,01), isso quer dizer que nossa média teórica está dentro do intervalo de confiança, portanto aceitamos a hipótese nula de que a média observada é similar a média teórica.</p>
<p>O nível de significância a aplicar nos seus dados depende das informações que possui sobre o organismo e o ambiente que está estudando. Apesar da regra-de-bolso dizer 0,05 e por padrão o R definir esse nível de significância é necessário discutir o que ele representa para seus dados e qual a implicação para sua hipótese e as medidas que serão tomadas. Uma dica importante é: reporte sempre o intervalo de confiança, indique o nível de significância (consiste em: 1 menos o nível de confiança) que foi aplicado e no seu texto deixe claro a escolha do nível de significância, principalmente se for diferente do que é definido como padrão.</p>
<p><strong>BÔNUS:</strong></p>
<p>Embora não seja comum, podemos plotar um gráfico que represente o nosso resultado estatístico como uma curva de densidade no qual é representado o valor do teste-t, o grau de liberdade e o valor de probabilidade associado. Para isso vamos usar um pacote o qual precisa ser instalado chamado “webr” e precisamos carrega-lo usando a função library(). Após isso é só inserir a função que desenvolve o teste-t dentro da função plot(). Veja o resultado para ambos os níveis de confiança estabelecidos previamente. OBS: Uma vez instalado o pacote não precisa instala-lo novamente.</p>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb166-1" data-line-number="1"><span class="co">## install.packages(&quot;webr&quot;)</span></a>
<a class="sourceLine" id="cb166-2" data-line-number="2"><span class="kw">library</span>(webr)</a></code></pre></div>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb167-1" data-line-number="1"><span class="kw">plot</span>(<span class="kw">t.test</span>(<span class="dt">x =</span> cracas, <span class="dt">mu =</span> teorico, <span class="dt">conf.level =</span> <span class="fl">0.95</span>))</a></code></pre></div>
<div class="figure"><span id="fig:cracas-dens-95"></span>
<img src="livroR-1.0_files/figure-html/cracas-dens-95-1.png" alt="Curva de densidade representando o valor do teste-t bicaudal para o tamanho das cracas em relação a média teórica a um intervalo de confiança de 95%. O ponto azul indica o valor do teste." width="672" />
<p class="caption">
Figura 4.4: Curva de densidade representando o valor do teste-t bicaudal para o tamanho das cracas em relação a média teórica a um intervalo de confiança de 95%. O ponto azul indica o valor do teste.
</p>
</div>
<div class="sourceCode" id="cb168"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb168-1" data-line-number="1"><span class="kw">plot</span>(<span class="kw">t.test</span>(<span class="dt">x =</span> cracas, <span class="dt">mu =</span> teorico, <span class="dt">conf.level =</span> <span class="fl">0.99</span>))</a></code></pre></div>
<div class="figure"><span id="fig:cracas-dens-99"></span>
<img src="livroR-1.0_files/figure-html/cracas-dens-99-1.png" alt="Curva de densidade representando o valor do teste-t bicaudal para o tamanho das cracas em relação a média teórica a um intervalo de confiança de 99%. O ponto azul indica o valor do teste." width="672" />
<p class="caption">
Figura 4.5: Curva de densidade representando o valor do teste-t bicaudal para o tamanho das cracas em relação a média teórica a um intervalo de confiança de 99%. O ponto azul indica o valor do teste.
</p>
</div>
<p>Verifique que esses plots nos fornecem as curvas do teste-t aos intervaloe de confiança de 95% (Figura <a href="teste-t-.html#fig:cracas-dens-95">4.4</a>) e 99% (Figura <a href="teste-t-.html#fig:cracas-dens-99">4.5</a>), demarca os limites inferior e superior de vermelho e marca como ponto azul na curva de densidade o valor do teste-t associado. Como esse valor está dentro da região demarcada no intervalo de confiança de 95%, neste caso rejeitamos a hipótese nula e como no intervalo de confiança de 99% o ponto azul está fora da região demarcada aceitamos a hipótese nula.</p>
</div>
<div id="teste-t-para-duas-amostras" class="section level2">
<h2><span class="header-section-number">4.2</span> Teste-t para duas amostras</h2>
<p>Conduzimos esse teste quando objetivamos comparar se a média de dois grupos (= amostras, populações etc) são similares. Portanto para sua realização é necessário uma variável mensurável e uma variável categórica com 2 grupos.</p>
<p>Ou seja, partindo desse objetivo as hipóteses nula e alternativa desse teste são as seguintes:</p>
<p>H0: A diferença na média da variável quantitativa dos grupos é igual a 0;</p>
<p>HA: A diferença na média da variável quantitativa dos grupos é diferente de 0;</p>
<p>Outra forma de apresentarmos a hipótese relativa a esste teste é:</p>
<p>H0: A média da variável quantitativa é igual entre grupos;</p>
<p>HA: A média da variável quantitativa é diferente entre grupos;</p>
<p>Outra forma de escrevermos a hipótese é em relação a caudalidade do teste e, se unicaudal, pode ser escrita da seguinte forma:</p>
<p>H0: A média da variável quantitativa é maior ou igual (ou menor ou igual) entre grupos;</p>
<p>HA: A média da variável quantitativa é menor (ou maior) entre grupos;</p>
<p>A partir desse teste alguns pressupostos estatísticos precisam ser avaliados e portanto algumas análises precisam ser realizadas antes da interpretação do resultado do teste-t. Pressupostos como normalidade (ambos os grupos devem provir de uma população com distribuição normal) e homocedasticidade (A variância entre os dois grupos devem ser iguais). Demonstraremos a frente como realizar alguns desses testes. Mas, primeiro vamos gerar os dados a serem trabalhados para esta etapa. Execute o código abaixo e você irá visualizar no “environment” do seu RStudio um objeto chamado “gastropode” que corresponde a um data frame com o conjunto de dados que iremos trabalhar.</p>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb169-1" data-line-number="1">grupos &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="kw">rep</span>(<span class="dt">x =</span> <span class="st">&quot;Alimento A&quot;</span>, <span class="dv">50</span>), <span class="kw">rep</span>(<span class="dt">x =</span> <span class="st">&quot;Alimento B&quot;</span>, <span class="dv">50</span>))</a>
<a class="sourceLine" id="cb169-2" data-line-number="2"><span class="kw">set.seed</span>(<span class="dv">123</span>)</a>
<a class="sourceLine" id="cb169-3" data-line-number="3">alimento.A &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dt">n =</span> <span class="dv">50</span>, <span class="dt">mean =</span> <span class="fl">0.7</span>, <span class="dt">sd =</span> <span class="fl">0.2</span>)</a>
<a class="sourceLine" id="cb169-4" data-line-number="4"><span class="kw">set.seed</span>(<span class="dv">4321</span>)</a>
<a class="sourceLine" id="cb169-5" data-line-number="5">alimento.B &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dt">n =</span> <span class="dv">50</span>, <span class="dt">mean =</span> <span class="fl">0.2</span>, <span class="dt">sd =</span> <span class="fl">0.2</span>)</a>
<a class="sourceLine" id="cb169-6" data-line-number="6">Alimento &lt;-<span class="st"> </span><span class="kw">c</span>(alimento.A, alimento.B)</a>
<a class="sourceLine" id="cb169-7" data-line-number="7">gastropode &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(<span class="kw">cbind</span>(grupos, <span class="kw">round</span>(Alimento, <span class="dv">3</span>)))</a>
<a class="sourceLine" id="cb169-8" data-line-number="8"><span class="kw">colnames</span>(gastropode) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Alimento&quot;</span>, <span class="st">&quot;Peso&quot;</span>)</a>
<a class="sourceLine" id="cb169-9" data-line-number="9"><span class="kw">rm</span>(<span class="dt">list =</span> <span class="st">&quot;grupos&quot;</span>, <span class="st">&quot;alimento.A&quot;</span>, <span class="st">&quot;alimento.B&quot;</span>, <span class="st">&quot;Alimento&quot;</span>)</a></code></pre></div>
<p><span style="color: red;">Neste momento não entraremos em detalhes sobre os comandos aplicados para construção desses dados. Caso seja do seu interesse consulte o apêndice, no final do livro.</span></p>
<p>Vamos, agora, verificar os dados por meio da função <em>head()</em> e a estrutura dos dados por meio da função <em>str()</em> e alterar a estrutura dos dados se necessário.</p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb170-1" data-line-number="1"><span class="kw">head</span>(gastropode)</a></code></pre></div>
<pre><code>##     Alimento  Peso
## 1 Alimento A 0.588
## 2 Alimento A 0.654
## 3 Alimento A 1.012
## 4 Alimento A 0.714
## 5 Alimento A 0.726
## 6 Alimento A 1.043</code></pre>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb172-1" data-line-number="1"><span class="kw">str</span>(gastropode)</a></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    100 obs. of  2 variables:
##  $ Alimento: chr  &quot;Alimento A&quot; &quot;Alimento A&quot; &quot;Alimento A&quot; &quot;Alimento A&quot; ...
##  $ Peso    : chr  &quot;0.588&quot; &quot;0.654&quot; &quot;1.012&quot; &quot;0.714&quot; ...</code></pre>
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb174-1" data-line-number="1">gastropode<span class="op">$</span>Alimento &lt;-<span class="st"> </span><span class="kw">as.factor</span>(gastropode<span class="op">$</span>Alimento)</a>
<a class="sourceLine" id="cb174-2" data-line-number="2">gastropode<span class="op">$</span>Peso &lt;-<span class="st"> </span><span class="kw">as.numeric</span>(gastropode<span class="op">$</span>Peso)</a>
<a class="sourceLine" id="cb174-3" data-line-number="3"><span class="kw">str</span>(gastropode)</a></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    100 obs. of  2 variables:
##  $ Alimento: Factor w/ 2 levels &quot;Alimento A&quot;,&quot;Alimento B&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ Peso    : num  0.588 0.654 1.012 0.714 0.726 ...</code></pre>
<p>Agora que importamos e organizamos nossa planilha vamos analisar nosso exemplo.</p>
<p>100 indivíduos de uma espécie de gastropode foi coletada e mantida em cultivo para avaliação da dieta. 50 indivíduos foram mantidos com uma dieta rica no Alimento A e 50 indivíduos com uma dieta rica no Alimento B. Todos os indivíduos foram pesados antes e depois do experimento. A planilha a seguir informa a alteração de peso dos organismos, em gramas, após a dieta oferecida.</p>
<p>Antes de conduzirmos o teste-t vamos praticar fazendo a avaliação gráfica e númerica dos dados.</p>
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb176-1" data-line-number="1"><span class="kw">hist</span>(gastropode<span class="op">$</span>Peso [gastropode<span class="op">$</span>Alimento <span class="op">==</span><span class="st"> &quot;Alimento A&quot;</span>], </a>
<a class="sourceLine" id="cb176-2" data-line-number="2">     <span class="dt">xlab =</span> <span class="st">&quot;Alteração do peso&quot;</span>, </a>
<a class="sourceLine" id="cb176-3" data-line-number="3">     <span class="dt">ylab =</span> <span class="st">&quot;Frequência&quot;, </span></a>
<a class="sourceLine" id="cb176-4" data-line-number="4"><span class="st">     main = &quot;</span>Alimento A<span class="st">&quot;, </span></a>
<a class="sourceLine" id="cb176-5" data-line-number="5"><span class="st">     ylim = c(0, 20),</span></a>
<a class="sourceLine" id="cb176-6" data-line-number="6"><span class="st">     xlim = c(-0.5, 1.5))</span></a></code></pre></div>
<div class="figure"><span id="fig:hist-ali-A"></span>
<img src="livroR-1.0_files/figure-html/hist-ali-A-1.png" alt="Histograma com valores da mudança do peso dos gastrópodes após a dieta com o Alimento A" width="672" />
<p class="caption">
Figura 4.6: Histograma com valores da mudança do peso dos gastrópodes após a dieta com o Alimento A
</p>
</div>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb177-1" data-line-number="1"><span class="kw">hist</span>(gastropode<span class="op">$</span>Peso [gastropode<span class="op">$</span>Alimento <span class="op">==</span><span class="st"> &quot;Alimento B&quot;</span>], </a>
<a class="sourceLine" id="cb177-2" data-line-number="2">     <span class="dt">xlab =</span> <span class="st">&quot;Alteração do peso&quot;</span>, </a>
<a class="sourceLine" id="cb177-3" data-line-number="3">     <span class="dt">ylab =</span> <span class="st">&quot;Frequência&quot;, </span></a>
<a class="sourceLine" id="cb177-4" data-line-number="4"><span class="st">     main = &quot;</span>Alimento B<span class="st">&quot;,</span></a>
<a class="sourceLine" id="cb177-5" data-line-number="5"><span class="st">     ylim = c(0, 20),</span></a>
<a class="sourceLine" id="cb177-6" data-line-number="6"><span class="st">     xlim = c(-0.5, 1.5))</span></a></code></pre></div>
<div class="figure"><span id="fig:hist-ali-B"></span>
<img src="livroR-1.0_files/figure-html/hist-ali-B-1.png" alt="Histograma com valores da mudança do peso dos gastrópodes após a dieta com o Alimento B" width="672" />
<p class="caption">
Figura 4.7: Histograma com valores da mudança do peso dos gastrópodes após a dieta com o Alimento B
</p>
</div>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb178-1" data-line-number="1"><span class="kw">boxplot</span>(Peso <span class="op">~</span><span class="st"> </span>Alimento, <span class="dt">data =</span> gastropode)</a></code></pre></div>
<div class="figure"><span id="fig:box-ali"></span>
<img src="livroR-1.0_files/figure-html/box-ali-1.png" alt="Boxplot com os valores da alteração do peso dos gastrópodes por tipo de alimento" width="672" />
<p class="caption">
Figura 4.8: Boxplot com os valores da alteração do peso dos gastrópodes por tipo de alimento
</p>
</div>
<p>Os comandos acima realizam: o histograma dos dados para Alimento A (Figura <a href="teste-t-.html#fig:hist-ali-A">4.6</a>), o histograma dos dados para Alimento B (Figura <a href="teste-t-.html#fig:hist-ali-B">4.7</a>) e o boxplot para ambos os dados (Figura <a href="teste-t-.html#fig:box-ali">4.8</a>), respectivamente.</p>
<p>Os 2 primeiros gráficos consistem em histogramas em relação aos dados de peso por Alimento. Na primeira linha indicamos a variável peso dentro da planilha gastropode por meio do operador matemático $ (cifrão) e selecionamos os dados correspondentes ao Alimento utilizando colchetes [] dentro do qual selecionamos a variável Alimento dentro da planilha gastropode e por meio do sinal de igual duplicado (==) indicamos entre aspas (&quot;“) o grupo (ou categoria) que desejamos. Os demais argumentos já são bem conhecidos e iguais para ambos os histogramas, diferindo apenas o título do gráfico que é definido pelo argumento”main&quot;.</p>
<p>O Boxplot resume os dados por Alimento e nos indica outras métricas (quartis), como vimos anteriormente no tópico sobre gráficos.</p>
<p>Mas se desejarmos observar os valores númericos que resumem os dados, podemos seguir o que aprendemos anteriormente.</p>
<div class="sourceCode" id="cb179"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb179-1" data-line-number="1"><span class="kw">summary</span>(gastropode)</a></code></pre></div>
<pre><code>##        Alimento       Peso        
##  Alimento A:50   Min.   :-0.1180  
##  Alimento B:50   1st Qu.: 0.2172  
##                  Median : 0.4475  
##                  Mean   : 0.4652  
##                  3rd Qu.: 0.6843  
##                  Max.   : 1.1340</code></pre>
<div class="sourceCode" id="cb181"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb181-1" data-line-number="1"><span class="kw">mean</span>(gastropode<span class="op">$</span>Peso)</a></code></pre></div>
<pre><code>## [1] 0.46519</code></pre>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb183-1" data-line-number="1"><span class="kw">mean</span>(gastropode<span class="op">$</span>Peso [gastropode<span class="op">$</span>Alimento <span class="op">==</span><span class="st"> &quot;Alimento A&quot;</span>])</a></code></pre></div>
<pre><code>## [1] 0.7069</code></pre>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb185-1" data-line-number="1"><span class="kw">mean</span>(gastropode<span class="op">$</span>Peso [gastropode<span class="op">$</span>Alimento <span class="op">==</span><span class="st"> &quot;Alimento B&quot;</span>])</a></code></pre></div>
<pre><code>## [1] 0.22348</code></pre>
<p>Utilizando o pacote Rmisc temos uma forma mais simples de escrita e eficiente para observar esses valores e algumas outras métricas (ex.: número amostral, média, desvio padrão, erro padrão e intervalo de confiança).</p>
<div class="sourceCode" id="cb187"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb187-1" data-line-number="1"><span class="kw">library</span>(Rmisc)</a>
<a class="sourceLine" id="cb187-2" data-line-number="2"><span class="kw">summarySE</span>(<span class="dt">data =</span> gastropode, <span class="dt">measurevar =</span> <span class="st">&quot;Peso&quot;</span>, <span class="dt">groupvars =</span> <span class="st">&quot;Alimento&quot;</span>)</a></code></pre></div>
<pre><code>##     Alimento  N    Peso        sd         se         ci
## 1 Alimento A 50 0.70690 0.1852070 0.02619223 0.05263525
## 2 Alimento B 50 0.22348 0.1573551 0.02225337 0.04471982</code></pre>
<p>Ok, até aqui observamos como estão os nossos dados e podemos ver que a administração da Alimento A resultou em um maior ganho de peso pelos gastropodes do que a Alimento B. Mas será que o que observamos grafica e numericamente se reflete estatisticamente? Vamos a nossa avaliação dos pressupostos do teste-t para duas amostras e se cumpridos para a avaliação do teste-t.</p>
<p>Uma das formas mais convencionais de avaliar a normalidade é pelo teste de shapiro-wilks e a homocedasticidade pelo teste de Bartlett. Vamos avalia-las.</p>
<div class="sourceCode" id="cb189"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb189-1" data-line-number="1"><span class="kw">shapiro.test</span>(gastropode<span class="op">$</span>Peso [gastropode<span class="op">$</span>Alimento <span class="op">==</span><span class="st"> &quot;Alimento A&quot;</span>])</a></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  gastropode$Peso[gastropode$Alimento == &quot;Alimento A&quot;]
## W = 0.98923, p-value = 0.9266</code></pre>
<div class="sourceCode" id="cb191"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb191-1" data-line-number="1"><span class="kw">shapiro.test</span>(gastropode<span class="op">$</span>Peso [gastropode<span class="op">$</span>Alimento <span class="op">==</span><span class="st"> &quot;Alimento B&quot;</span>])</a></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  gastropode$Peso[gastropode$Alimento == &quot;Alimento B&quot;]
## W = 0.98059, p-value = 0.5769</code></pre>
<div class="sourceCode" id="cb193"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb193-1" data-line-number="1"><span class="kw">bartlett.test</span>(Peso <span class="op">~</span><span class="st"> </span>Alimento, <span class="dt">data =</span> gastropode)</a></code></pre></div>
<pre><code>## 
##  Bartlett test of homogeneity of variances
## 
## data:  Peso by Alimento
## Bartlett&#39;s K-squared = 1.2826, df = 1, p-value = 0.2574</code></pre>
<p>Como podemos observar, ambos os grupos apresentam dados normais e homocedásticos, para um nível de confiança de 95%, já que o p-value foi superior a 0,05. Dessa forma vamos dar continuidade a nossa análise e verificar se as médias dos grupos são diferentes.</p>
<div class="sourceCode" id="cb195"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb195-1" data-line-number="1"><span class="kw">t.test</span>(Peso <span class="op">~</span><span class="st"> </span>Alimento, </a>
<a class="sourceLine" id="cb195-2" data-line-number="2">       <span class="dt">data =</span> gastropode,</a>
<a class="sourceLine" id="cb195-3" data-line-number="3">       <span class="dt">var.equal =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb195-4" data-line-number="4">       <span class="dt">conf.level =</span> <span class="fl">0.95</span>)</a></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  Peso by Alimento
## t = 14.065, df = 98, p-value &lt; 2.2e-16
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  0.4152153 0.5516247
## sample estimates:
## mean in group Alimento A mean in group Alimento B 
##                  0.70690                  0.22348</code></pre>
<p>Repare que a forma da escrita se alterou um pouco. Mas como podem ver, nada complicado. Agora escrevemos a variável quantitativa (peso) em função da (~) variável categórica (Alimento). Guarde bem essa forma de escrita pois ela será utilizada para praticamente todos os testes a partir daqui e para inúmeras outras funções. Adcionamos o argumento “data” que indica a planilha de onde estamos utilizando as variáveis, o argumento “var.equal” o qual indica que a variância entre os grupos é igual e o argumento “conf.level” o qual define o nível de confiança com qual estamos trabalhando.</p>
<p>De acordo com nosso resultado podemos ver que o o valor do teste-t é 14,065, o grau de liberdade de 98 (o qual consiste no total de observações subtraído de um por grupo), o valor de probabilidade associado ao teste (<span class="math inline">\(2,2\times10^{-16}\)</span>), o intervalo de confiança de 95% (0,415 e 0,551) que refere-se a diferença da média entre os grupos (a diferença da média dos grupos é: 0,70690 - 0,22348 = 0,48342), ou seja, o intervalo de confiança é em função dessa diferença e as últimas linhas do resultado representam as médias de alteração do peso para cada Alimento (Alimento A = 0,70690 e Alimento B = 0,22348). De acordo com esse resultado refutamos a hipótese nula de que as médias são similares. Portanto podemos dizer que dependendo da Alimento (A ou B) utilizada na dieta podemos ter diferentes alterações no peso dos gastropodes.</p>
<p>Da mesma forma que avaliamos para o teste-t de uma amostra, podemos plotar o resultado como um gráfico da função de densidade do teste-t. Só devemos lembrar de carregar o pacote “webr”.</p>
<div class="sourceCode" id="cb197"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb197-1" data-line-number="1"><span class="kw">library</span>(webr)</a>
<a class="sourceLine" id="cb197-2" data-line-number="2"><span class="kw">plot</span>(<span class="kw">t.test</span>(Peso <span class="op">~</span><span class="st"> </span>Alimento, </a>
<a class="sourceLine" id="cb197-3" data-line-number="3">            <span class="dt">data =</span> gastropode,</a>
<a class="sourceLine" id="cb197-4" data-line-number="4">            <span class="dt">var.equal =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb197-5" data-line-number="5">            <span class="dt">conf.level =</span> <span class="fl">0.95</span>))</a></code></pre></div>
<div class="figure"><span id="fig:testet-duas-dens"></span>
<img src="livroR-1.0_files/figure-html/testet-duas-dens-1.png" alt="Curva de densidade representando o valor do teste-t bicaudal para a alteração do peso de gastrópodes em relação ao alimento a um intervalo de confiança de 95%. O ponto azul indica o valor do teste." width="672" />
<p class="caption">
Figura 4.9: Curva de densidade representando o valor do teste-t bicaudal para a alteração do peso de gastrópodes em relação ao alimento a um intervalo de confiança de 95%. O ponto azul indica o valor do teste.
</p>
</div>
<p>Neste gráfico podemos ver que o resultado do teste-t (Figura <a href="teste-t-.html#fig:testet-duas-dens">4.9</a>), indicado pelo ponto azul, está muito além do nível da zona de rejeição, indicando que os dois grupos apresentam médias bem diferentes, ou seja, a diferença entre as duas médias é altamente significativa e diferente de 0.</p>
<p>Vamos exercitar nosso conhecimento em R e teste-t com um outro exemplo (Gere a planilha abaixo).</p>
<div class="sourceCode" id="cb198"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb198-1" data-line-number="1">grupos &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="kw">rep</span>(<span class="dt">x =</span> <span class="st">&quot;Ano 0&quot;</span>, <span class="dv">36</span>), <span class="kw">rep</span>(<span class="dt">x =</span> <span class="st">&quot;Ano 20&quot;</span>, <span class="dv">36</span>))</a>
<a class="sourceLine" id="cb198-2" data-line-number="2"><span class="kw">set.seed</span>(<span class="dv">245</span>)</a>
<a class="sourceLine" id="cb198-3" data-line-number="3">ano<span class="fl">.0</span> &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dt">n =</span> <span class="dv">36</span>, <span class="dt">mean =</span> <span class="fl">15.7</span>, <span class="dt">sd =</span> <span class="fl">0.2</span>) <span class="op">+</span><span class="st"> </span><span class="kw">runif</span>(<span class="dt">n =</span> <span class="dv">36</span>)</a>
<a class="sourceLine" id="cb198-4" data-line-number="4"><span class="kw">set.seed</span>(<span class="dv">356</span>)</a>
<a class="sourceLine" id="cb198-5" data-line-number="5">ano<span class="fl">.20</span> &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dt">n =</span> <span class="dv">36</span>, <span class="dt">mean =</span> <span class="fl">16.2</span>, <span class="dt">sd =</span> <span class="fl">0.5</span>) <span class="op">+</span><span class="st"> </span><span class="kw">runif</span>(<span class="dt">n =</span> <span class="dv">36</span>)</a>
<a class="sourceLine" id="cb198-6" data-line-number="6">ano &lt;-<span class="st"> </span><span class="kw">c</span>(ano<span class="fl">.0</span>, ano<span class="fl">.20</span>)</a>
<a class="sourceLine" id="cb198-7" data-line-number="7">lagoa &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(<span class="kw">cbind</span>(grupos, <span class="kw">round</span>(ano, <span class="dv">3</span>)))</a>
<a class="sourceLine" id="cb198-8" data-line-number="8"><span class="kw">colnames</span>(lagoa) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Ano&quot;</span>, <span class="st">&quot;Temperatura&quot;</span>)</a>
<a class="sourceLine" id="cb198-9" data-line-number="9"><span class="kw">rm</span>(<span class="dt">list =</span> <span class="st">&quot;grupos&quot;</span>, <span class="st">&quot;ano.0&quot;</span>, <span class="st">&quot;ano.20&quot;</span>, <span class="st">&quot;ano&quot;</span>)</a></code></pre></div>
<p>Imagine que durante um ano você mensurou a temperatura de uma lagoa três vezes por mês durante todos os meses ao longo de 1 ano. 20 anos depois você retornou a lagoa e mensurou novamente a temperatura três vezes por mês durante um ano. Considerando um nível de confiança de 99% a temperatura é igual ou diferente entre os anos?</p>
<p>A primeira coisa que devemos fazer é escrever nossa hipótese. Vamos a ela.</p>
<p>H0: A média da temperatura é igual entre os anos;</p>
<p>HA: A média da temperatura é diferente entre os anos;</p>
<p>Com a hipótese construída vamos verificar a estrutura dos dados (modificar se necessário) e sumarizar nossos dados gráfica e matematicamente.</p>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb199-1" data-line-number="1"><span class="kw">head</span>(lagoa)</a></code></pre></div>
<pre><code>##     Ano Temperatura
## 1 Ano 0      16.345
## 2 Ano 0      16.383
## 3 Ano 0      15.727
## 4 Ano 0      16.058
## 5 Ano 0      15.842
## 6 Ano 0      16.158</code></pre>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb201-1" data-line-number="1"><span class="kw">str</span>(lagoa)</a></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    72 obs. of  2 variables:
##  $ Ano        : chr  &quot;Ano 0&quot; &quot;Ano 0&quot; &quot;Ano 0&quot; &quot;Ano 0&quot; ...
##  $ Temperatura: chr  &quot;16.345&quot; &quot;16.383&quot; &quot;15.727&quot; &quot;16.058&quot; ...</code></pre>
<div class="sourceCode" id="cb203"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb203-1" data-line-number="1">lagoa<span class="op">$</span>Ano &lt;-<span class="st"> </span><span class="kw">as.factor</span>(lagoa<span class="op">$</span>Ano)</a>
<a class="sourceLine" id="cb203-2" data-line-number="2">lagoa<span class="op">$</span>Temperatura &lt;-<span class="st"> </span><span class="kw">as.numeric</span>(lagoa<span class="op">$</span>Temperatura)</a>
<a class="sourceLine" id="cb203-3" data-line-number="3"><span class="kw">str</span>(lagoa)</a></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    72 obs. of  2 variables:
##  $ Ano        : Factor w/ 2 levels &quot;Ano 0&quot;,&quot;Ano 20&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ Temperatura: num  16.3 16.4 15.7 16.1 15.8 ...</code></pre>
<div class="sourceCode" id="cb205"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb205-1" data-line-number="1"><span class="kw">hist</span>(lagoa<span class="op">$</span>Temperatura [lagoa<span class="op">$</span>Ano <span class="op">==</span><span class="st"> &quot;Ano 0&quot;</span>], </a>
<a class="sourceLine" id="cb205-2" data-line-number="2">     <span class="dt">xlab =</span> <span class="st">&quot;Temperatura (°C)&quot;</span>, </a>
<a class="sourceLine" id="cb205-3" data-line-number="3">     <span class="dt">ylab =</span> <span class="st">&quot;Frequência&quot;, </span></a>
<a class="sourceLine" id="cb205-4" data-line-number="4"><span class="st">     main = &quot;</span>Ano <span class="dv">0</span><span class="st">&quot;, </span></a>
<a class="sourceLine" id="cb205-5" data-line-number="5"><span class="st">     ylim = c(0, 15),</span></a>
<a class="sourceLine" id="cb205-6" data-line-number="6"><span class="st">     xlim = c(15, 19))</span></a></code></pre></div>
<div class="figure"><span id="fig:hist-temp-0"></span>
<img src="livroR-1.0_files/figure-html/hist-temp-0-1.png" alt="Histograma com valores de temperatura da lagoa no Ano 0." width="672" />
<p class="caption">
Figura 4.10: Histograma com valores de temperatura da lagoa no Ano 0.
</p>
</div>
<div class="sourceCode" id="cb206"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb206-1" data-line-number="1"><span class="kw">hist</span>(lagoa<span class="op">$</span>Temperatura [lagoa<span class="op">$</span>Ano <span class="op">==</span><span class="st"> &quot;Ano 20&quot;</span>], </a>
<a class="sourceLine" id="cb206-2" data-line-number="2">     <span class="dt">xlab =</span> <span class="st">&quot;Temperatura (°C)&quot;</span>, </a>
<a class="sourceLine" id="cb206-3" data-line-number="3">     <span class="dt">ylab =</span> <span class="st">&quot;Frequência&quot;, </span></a>
<a class="sourceLine" id="cb206-4" data-line-number="4"><span class="st">     main = &quot;</span>Ano <span class="dv">20</span><span class="st">&quot;, </span></a>
<a class="sourceLine" id="cb206-5" data-line-number="5"><span class="st">     ylim = c(0, 15),</span></a>
<a class="sourceLine" id="cb206-6" data-line-number="6"><span class="st">     xlim = c(15, 19))</span></a></code></pre></div>
<div class="figure"><span id="fig:hist-temp-20"></span>
<img src="livroR-1.0_files/figure-html/hist-temp-20-1.png" alt="Histograma com valores de temperatura da lagoa no Ano 20." width="672" />
<p class="caption">
Figura 4.11: Histograma com valores de temperatura da lagoa no Ano 20.
</p>
</div>
<div class="sourceCode" id="cb207"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb207-1" data-line-number="1"><span class="kw">boxplot</span>(Temperatura <span class="op">~</span><span class="st"> </span>Ano, <span class="dt">data =</span> lagoa)</a></code></pre></div>
<div class="figure"><span id="fig:box-temp"></span>
<img src="livroR-1.0_files/figure-html/box-temp-1.png" alt="Boxplot com os valores de temperatura da lagoa por ano." width="672" />
<p class="caption">
Figura 4.12: Boxplot com os valores de temperatura da lagoa por ano.
</p>
</div>
<p>Como podem verificar os comandos para a análise gráfica não diferiu do que fizemos no exemplo anterior. Os comandos acima realizam: o histograma dos valores de temperatura no ano 0 (Figura <a href="teste-t-.html#fig:hist-temp-0">4.10</a>), o histograma dos valores de temperatura no ano 0 (Figura <a href="teste-t-.html#fig:hist-temp-20">4.11</a>) e o boxplot para ambos os dados (Figura <a href="teste-t-.html#fig:box-temp">4.12</a>), respectivamente. Quanto ao seu resultado podemos notar uma maior temperatura média anual da lagoa 20 anos depois da primeira amostragem.</p>
<div class="sourceCode" id="cb208"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb208-1" data-line-number="1"><span class="kw">summary</span>(lagoa)</a></code></pre></div>
<pre><code>##      Ano      Temperatura   
##  Ano 0 :36   Min.   :15.58  
##  Ano 20:36   1st Qu.:16.08  
##              Median :16.41  
##              Mean   :16.52  
##              3rd Qu.:16.86  
##              Max.   :18.74</code></pre>
<div class="sourceCode" id="cb210"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb210-1" data-line-number="1"><span class="kw">library</span>(Rmisc)</a>
<a class="sourceLine" id="cb210-2" data-line-number="2"><span class="kw">summarySE</span>(<span class="dt">data =</span> lagoa, <span class="dt">measurevar =</span> <span class="st">&quot;Temperatura&quot;</span>, <span class="dt">groupvars =</span> <span class="st">&quot;Ano&quot;</span>)</a></code></pre></div>
<pre><code>##      Ano  N Temperatura        sd         se        ci
## 1  Ano 0 36    16.14661 0.3301591 0.05502652 0.1117098
## 2 Ano 20 36    16.89750 0.6409853 0.10683089 0.2168782</code></pre>
<p>Aplicando a função <em>summarySE()</em> do pacote Rmisc obtivemos sumarizamos nossos dados como mostrado acima e em relação aos valores de média e desvios podemos observar que a média é bem próxima, mas será que elas são estatisticamente iguais? Para isso vamos realizar o teste-t.</p>
<p>Antes do teste vamos calcular os pressupostos do teste, normalidade e homocedasticidade.</p>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb212-1" data-line-number="1"><span class="kw">shapiro.test</span>(lagoa<span class="op">$</span>Temperatura [lagoa<span class="op">$</span>Ano <span class="op">==</span><span class="st"> &quot;Ano 0&quot;</span>])</a></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  lagoa$Temperatura[lagoa$Ano == &quot;Ano 0&quot;]
## W = 0.97181, p-value = 0.4771</code></pre>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb214-1" data-line-number="1"><span class="kw">shapiro.test</span>(lagoa<span class="op">$</span>Temperatura [lagoa<span class="op">$</span>Ano <span class="op">==</span><span class="st"> &quot;Ano 20&quot;</span>])</a></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  lagoa$Temperatura[lagoa$Ano == &quot;Ano 20&quot;]
## W = 0.9571, p-value = 0.1747</code></pre>
<div class="sourceCode" id="cb216"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb216-1" data-line-number="1"><span class="kw">bartlett.test</span>(Temperatura <span class="op">~</span><span class="st"> </span>Ano, <span class="dt">data =</span> lagoa)</a></code></pre></div>
<pre><code>## 
##  Bartlett test of homogeneity of variances
## 
## data:  Temperatura by Ano
## Bartlett&#39;s K-squared = 14.189, df = 1, p-value = 0.0001653</code></pre>
<p>Como podemos ver os dados são normais, porém não são homocedasticos (a variância não é igual entre os grupos). Neste caso podemos fazer um teste-t de Welch (este teste aplica uma correção quando as variâncias não são iguais). Contudo, o teste de Welch ele é comumente usado quando o N amostral é considerado baixo (menor que 10 para um dos dois grupos). Vamos Analisar o teste-t considerando a variância igual e desigual para ver se há diferença significativa no resultado do teste ou não.</p>
<div class="sourceCode" id="cb218"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb218-1" data-line-number="1"><span class="kw">t.test</span>(Temperatura <span class="op">~</span><span class="st"> </span>Ano, </a>
<a class="sourceLine" id="cb218-2" data-line-number="2">       <span class="dt">data =</span> lagoa,</a>
<a class="sourceLine" id="cb218-3" data-line-number="3">       <span class="dt">var.equal =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb218-4" data-line-number="4">       <span class="dt">conf.level =</span> <span class="fl">0.99</span>)</a></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  Temperatura by Ano
## t = -6.2486, df = 70, p-value = 2.837e-08
## alternative hypothesis: true difference in means is not equal to 0
## 99 percent confidence interval:
##  -1.069087 -0.432691
## sample estimates:
##  mean in group Ano 0 mean in group Ano 20 
##             16.14661             16.89750</code></pre>
<div class="sourceCode" id="cb220"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb220-1" data-line-number="1"><span class="kw">t.test</span>(Temperatura <span class="op">~</span><span class="st"> </span>Ano, </a>
<a class="sourceLine" id="cb220-2" data-line-number="2">       <span class="dt">data =</span> lagoa,</a>
<a class="sourceLine" id="cb220-3" data-line-number="3">       <span class="dt">var.equal =</span> <span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb220-4" data-line-number="4">       <span class="dt">conf.level =</span> <span class="fl">0.99</span>)</a></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  Temperatura by Ano
## t = -6.2486, df = 52.35, p-value = 7.594e-08
## alternative hypothesis: true difference in means is not equal to 0
## 99 percent confidence interval:
##  -1.0721092 -0.4296686
## sample estimates:
##  mean in group Ano 0 mean in group Ano 20 
##             16.14661             16.89750</code></pre>
<p>Como podem notar a forma de escrever o teste é similar ao exemplo anterior as alterações consistem nas variáveis e conjunto de dados utilizado e como foi pedido no teste a alteração do nível de confiança para 99% (conf.level = 0,99) e os dois teste-t (com variância igual e com variância desigual - Welch).</p>
<p>Olhando para os dois resultados ambos os testes demonstraram diferenças significativas entre os anos, pois o p-value foi menor que 0,01 (lembrar que como o nível de confiança foi alterado para 0,99 a significância só ocorrerá se o p-value for menor que 0,01, como é o caso). Porém podemos ver que não há muita diferença em relação aos valores de ambos os teste-t, pois como comunicamos a aplicação do teste-t de Welch apresenta maior importância quando as variâncias são desiguais e o número amostral de um dos grupos é muito pequeno.</p>
<p>Assim como fizemos anteriormente vamos olhar o resultado em relação a distribuição da função de densidade do teste-t para um nível de confiança de 99% (Figura <a href="teste-t-.html#fig:testet-duas-temp-dens">4.13</a>). Só devemos lembrar de carregar o pacote “webr” se ainda não foi carregado.</p>
<div class="sourceCode" id="cb222"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb222-1" data-line-number="1"><span class="kw">library</span>(webr)</a>
<a class="sourceLine" id="cb222-2" data-line-number="2"><span class="kw">plot</span>(<span class="kw">t.test</span>(Temperatura <span class="op">~</span><span class="st"> </span>Ano, </a>
<a class="sourceLine" id="cb222-3" data-line-number="3">            <span class="dt">data =</span> lagoa,</a>
<a class="sourceLine" id="cb222-4" data-line-number="4">            <span class="dt">var.equal =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb222-5" data-line-number="5">            <span class="dt">conf.level =</span> <span class="fl">0.99</span>))</a></code></pre></div>
<div class="figure"><span id="fig:testet-duas-temp-dens"></span>
<img src="livroR-1.0_files/figure-html/testet-duas-temp-dens-1.png" alt="Curva de densidade representando o valor do teste-t bicaudal para comparação da temperatura em um lago entre dois anos a um intervalo de confiança de 99%. O ponto azul indica o valor do teste." width="672" />
<p class="caption">
Figura 4.13: Curva de densidade representando o valor do teste-t bicaudal para comparação da temperatura em um lago entre dois anos a um intervalo de confiança de 99%. O ponto azul indica o valor do teste.
</p>
</div>
<p>De acordo com esse exemplo podemos afirmar que os anos diferem entre si e que em 20 anos a lagoa amostrada apresentou um aumento da temperatura.</p>
</div>
<div id="teste-t-pareado" class="section level2">
<h2><span class="header-section-number">4.3</span> Teste-t pareado</h2>
<p>Aplicamos este teste quando as duas amostras de uma variável categórica são independentes e desejamos verificar se elas são similares entre si. Contudo cada observação de ambas as amostras devem de alguma forma estar associadas para podermos dizer que ocorrem em pares. Neste caso as hipóteses são as seguintes:</p>
<p>H0: Não há diferença entre os pares de observações;</p>
<p>HA: Há diferença entre os pares de observações;</p>
<p>Matematicamente pode ser dita da seguinte forma:</p>
<p>H0: A diferença na média dos pares de observações é igual a 0;</p>
<p>HA: A diferença na média dos pares de observações é diferente de 0;</p>
<p>Vejamos um exemplo de como conduzir essa análise no R</p>
<p>Imagine que dois pesquisadores embarcaram com objetivo de fazer contagem de aves em alto mar. Após 20 dias de observações independentes entre os observadores obtivemos os dados abaixo.</p>
<p>Começaremos gerando os dados e a modificando se necessário.</p>
<div class="sourceCode" id="cb223"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb223-1" data-line-number="1">observadores &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="kw">rep</span>(<span class="dt">x =</span> <span class="st">&quot;Observador 1&quot;</span>, <span class="dv">20</span>), <span class="kw">rep</span>(<span class="dt">x =</span> <span class="st">&quot;Observador 2&quot;</span>, <span class="dv">20</span>))</a>
<a class="sourceLine" id="cb223-2" data-line-number="2"><span class="kw">set.seed</span>(<span class="dv">2328</span>)</a>
<a class="sourceLine" id="cb223-3" data-line-number="3">aves<span class="fl">.1</span> &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dt">n =</span> <span class="dv">20</span>, <span class="dt">mean =</span> <span class="dv">20</span>, <span class="dt">sd =</span> <span class="dv">1</span>) <span class="op">+</span><span class="st"> </span><span class="kw">runif</span>(<span class="dt">n =</span> <span class="dv">20</span>)</a>
<a class="sourceLine" id="cb223-4" data-line-number="4"><span class="kw">set.seed</span>(<span class="dv">3230</span>)</a>
<a class="sourceLine" id="cb223-5" data-line-number="5">aves<span class="fl">.2</span> &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dt">n =</span> <span class="dv">20</span>, <span class="dt">mean =</span> <span class="dv">21</span>, <span class="dt">sd =</span> <span class="dv">2</span>) <span class="op">+</span><span class="st"> </span><span class="kw">runif</span>(<span class="dt">n =</span> <span class="dv">20</span>)</a>
<a class="sourceLine" id="cb223-6" data-line-number="6">dia &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Dia 1&quot;</span>, <span class="st">&quot;Dia 2&quot;</span>, <span class="st">&quot;Dia 3&quot;</span>, <span class="st">&quot;Dia 4&quot;</span>, <span class="st">&quot;Dia 5&quot;</span>, <span class="st">&quot;Dia 6&quot;</span>, <span class="st">&quot;Dia 7&quot;</span>, <span class="st">&quot;Dia 8&quot;</span>, <span class="st">&quot;Dia 9&quot;</span>, <span class="st">&quot;Dia 10&quot;</span>, <span class="st">&quot;Dia 11&quot;</span>, <span class="st">&quot;Dia 12&quot;</span>, <span class="st">&quot;Dia 13&quot;</span>, <span class="st">&quot;Dia 14&quot;</span>, <span class="st">&quot;Dia 15&quot;</span>, <span class="st">&quot;Dia 16&quot;</span>, <span class="st">&quot;Dia 17&quot;</span>, <span class="st">&quot;Dia 18&quot;</span>, <span class="st">&quot;Dia 19&quot;</span>, <span class="st">&quot;Dia 20&quot;</span>)</a>
<a class="sourceLine" id="cb223-7" data-line-number="7">aves &lt;-<span class="st"> </span><span class="kw">c</span>(aves<span class="fl">.1</span>, aves<span class="fl">.2</span>)</a>
<a class="sourceLine" id="cb223-8" data-line-number="8">aves &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(<span class="kw">cbind</span>(dia, <span class="kw">round</span>(aves<span class="fl">.1</span>, <span class="dv">0</span>), <span class="kw">round</span>(aves<span class="fl">.2</span>, <span class="dv">0</span>)))</a>
<a class="sourceLine" id="cb223-9" data-line-number="9"><span class="kw">colnames</span>(aves) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Dia&quot;</span>, <span class="st">&quot;Observador 1&quot;</span>, <span class="st">&quot;Observador 2&quot;</span>)</a>
<a class="sourceLine" id="cb223-10" data-line-number="10"><span class="kw">rm</span>(<span class="dt">list =</span> <span class="st">&quot;observadores&quot;</span>, <span class="st">&quot;aves.1&quot;</span>, <span class="st">&quot;aves.2&quot;</span>, <span class="st">&quot;dia&quot;</span>)</a></code></pre></div>
<p><span style="color: red;">Neste momento não entraremos em detalhes sobre os comandos aplicados para construção desses dados. Caso seja do seu interesse consulte o apêndice, no final do livro.</span></p>
<div class="sourceCode" id="cb224"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb224-1" data-line-number="1"><span class="kw">head</span>(aves)</a></code></pre></div>
<pre><code>##     Dia Observador 1 Observador 2
## 1 Dia 1           19           20
## 2 Dia 2           20           22
## 3 Dia 3           18           23
## 4 Dia 4           22           18
## 5 Dia 5           22           22
## 6 Dia 6           22           23</code></pre>
<div class="sourceCode" id="cb226"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb226-1" data-line-number="1"><span class="kw">str</span>(aves)</a></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    20 obs. of  3 variables:
##  $ Dia         : chr  &quot;Dia 1&quot; &quot;Dia 2&quot; &quot;Dia 3&quot; &quot;Dia 4&quot; ...
##  $ Observador 1: chr  &quot;19&quot; &quot;20&quot; &quot;18&quot; &quot;22&quot; ...
##  $ Observador 2: chr  &quot;20&quot; &quot;22&quot; &quot;23&quot; &quot;18&quot; ...</code></pre>
<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb228-1" data-line-number="1">aves<span class="op">$</span>Dia &lt;-<span class="st"> </span><span class="kw">as.factor</span>(aves<span class="op">$</span>Dia)</a>
<a class="sourceLine" id="cb228-2" data-line-number="2">aves<span class="op">$</span><span class="st">`</span><span class="dt">Observador 1</span><span class="st">`</span> &lt;-<span class="st"> </span><span class="kw">as.numeric</span>(aves<span class="op">$</span><span class="st">`</span><span class="dt">Observador 1</span><span class="st">`</span>)</a>
<a class="sourceLine" id="cb228-3" data-line-number="3">aves<span class="op">$</span><span class="st">`</span><span class="dt">Observador 2</span><span class="st">`</span> &lt;-<span class="st"> </span><span class="kw">as.numeric</span>(aves<span class="op">$</span><span class="st">`</span><span class="dt">Observador 2</span><span class="st">`</span>)</a>
<a class="sourceLine" id="cb228-4" data-line-number="4"><span class="kw">str</span>(aves)</a></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    20 obs. of  3 variables:
##  $ Dia         : Factor w/ 20 levels &quot;Dia 1&quot;,&quot;Dia 10&quot;,..: 1 12 14 15 16 17 18 19 20 2 ...
##  $ Observador 1: num  19 20 18 22 22 22 21 20 22 21 ...
##  $ Observador 2: num  20 22 23 18 22 23 20 24 22 24 ...</code></pre>
<p>Agora definimos nossas hipóteses</p>
<p>H0: Não há diferença entre os pares de observações dos pesquisadores;</p>
<p>HA: Há diferença entre os pares de observações dos pesquisadores;</p>
<p>Vamos sumarizar os dados gráfica e estatisticamente</p>
<div class="sourceCode" id="cb230"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb230-1" data-line-number="1"><span class="kw">hist</span>(aves<span class="op">$</span><span class="st">`</span><span class="dt">Observador 1</span><span class="st">`</span>, </a>
<a class="sourceLine" id="cb230-2" data-line-number="2">     <span class="dt">xlab =</span> <span class="st">&quot;Observações&quot;</span>, </a>
<a class="sourceLine" id="cb230-3" data-line-number="3">     <span class="dt">ylab =</span> <span class="st">&quot;Frequência&quot;, </span></a>
<a class="sourceLine" id="cb230-4" data-line-number="4"><span class="st">     main = &quot;</span>Observador <span class="dv">1</span><span class="st">&quot;, </span></a>
<a class="sourceLine" id="cb230-5" data-line-number="5"><span class="st">     ylim = c(0, 10),</span></a>
<a class="sourceLine" id="cb230-6" data-line-number="6"><span class="st">     xlim = c(18, 25))</span></a></code></pre></div>
<div class="figure"><span id="fig:hist-par-obs1"></span>
<img src="livroR-1.0_files/figure-html/hist-par-obs1-1.png" alt="Histograma com a frequência de observações de aves, por 20 dias, pelo observador 1" width="672" />
<p class="caption">
Figura 4.14: Histograma com a frequência de observações de aves, por 20 dias, pelo observador 1
</p>
</div>
<div class="sourceCode" id="cb231"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb231-1" data-line-number="1"><span class="kw">hist</span>(aves<span class="op">$</span><span class="st">`</span><span class="dt">Observador 2</span><span class="st">`</span>, </a>
<a class="sourceLine" id="cb231-2" data-line-number="2">     <span class="dt">xlab =</span> <span class="st">&quot;Observações&quot;</span>, </a>
<a class="sourceLine" id="cb231-3" data-line-number="3">     <span class="dt">ylab =</span> <span class="st">&quot;Frequência&quot;, </span></a>
<a class="sourceLine" id="cb231-4" data-line-number="4"><span class="st">     main = &quot;</span>Observador <span class="dv">2</span><span class="st">&quot;, </span></a>
<a class="sourceLine" id="cb231-5" data-line-number="5"><span class="st">     ylim = c(0, 10),</span></a>
<a class="sourceLine" id="cb231-6" data-line-number="6"><span class="st">     xlim = c(18, 25))</span></a></code></pre></div>
<div class="figure"><span id="fig:hist-par-obs2"></span>
<img src="livroR-1.0_files/figure-html/hist-par-obs2-1.png" alt="Histograma com a frequência de observações de aves, por 20 dias, pelo observador 2" width="672" />
<p class="caption">
Figura 4.15: Histograma com a frequência de observações de aves, por 20 dias, pelo observador 2
</p>
</div>
<div class="sourceCode" id="cb232"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb232-1" data-line-number="1"><span class="kw">boxplot</span>(aves<span class="op">$</span><span class="st">`</span><span class="dt">Observador 1</span><span class="st">`</span>, </a>
<a class="sourceLine" id="cb232-2" data-line-number="2">        aves<span class="op">$</span><span class="st">`</span><span class="dt">Observador 2</span><span class="st">`</span>, </a>
<a class="sourceLine" id="cb232-3" data-line-number="3">        <span class="dt">names =</span> <span class="kw">c</span>(<span class="st">&quot;Observador 1&quot;</span>, <span class="st">&quot;Observador 2&quot;</span>),</a>
<a class="sourceLine" id="cb232-4" data-line-number="4">        <span class="dt">ylab =</span> <span class="st">&quot;Frequência de Observações&quot;</span>)</a></code></pre></div>
<div class="figure"><span id="fig:box-par-ave"></span>
<img src="livroR-1.0_files/figure-html/box-par-ave-1.png" alt="Boxplot com as frequências de observações de aves por 20 dias de 2 observadores." width="672" />
<p class="caption">
Figura 4.16: Boxplot com as frequências de observações de aves por 20 dias de 2 observadores.
</p>
</div>
<p>Como podem verificar os comandos para a análise gráfica não diferiu do que fizemos nos exemplos anteriores para os histogramas (Figura <a href="teste-t-.html#fig:hist-par-obs1">4.14</a> e <a href="teste-t-.html#fig:hist-par-obs2">4.15</a>) e pouco diferiu para o boxplot ((Figura <a href="teste-t-.html#fig:box-par-ave">4.16</a>).</p>
<p>A estrutura da planilha é diferente das anteriores o que por sua vez alterou a mudança na escrita do comando para construção para o boxplot. Desta não mais utilizamos o til (~), mas inserimos o nome da planilha seguido pelo operador matemático $ (cifrão) mais o nome da variável quantitativa que queremos representar. Inserimos também outros 2 argumentos que são “names” com dois nomes concatenados pela função c() que representam as variáveis quantitativas na ordem em que foram inseridas e o argumento “ylab” que dá nome ao eixo y.</p>
<div class="sourceCode" id="cb233"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb233-1" data-line-number="1"><span class="kw">summary</span>(aves)</a></code></pre></div>
<pre><code>##       Dia      Observador 1    Observador 2  
##  Dia 1  : 1   Min.   :18.00   Min.   :18.00  
##  Dia 10 : 1   1st Qu.:20.00   1st Qu.:20.00  
##  Dia 11 : 1   Median :21.00   Median :22.00  
##  Dia 12 : 1   Mean   :20.70   Mean   :21.90  
##  Dia 13 : 1   3rd Qu.:21.25   3rd Qu.:23.25  
##  Dia 14 : 1   Max.   :22.00   Max.   :25.00  
##  (Other):14</code></pre>
<p>Como podemos notar, devido a organização dos dados na planilha a função <em>summary()</em> já sumariza de maneira adequada nossos dados.</p>
<p>Em relação ao resumo dos nossos dados podemos observar que o observador 2 contabilizou um número maior de aves que o observador 1, mas será que a diferença no número de observações é nulo (0) ou é diferente. ou seja será que a média de observação entre os observadores é similar?</p>
<p>O teste-t pareado não aparesenta pressuposto quanto aos dados, porém como ele avalia a diferença entre dois grupos o pressuposto requerido é a normalidade da diferença dos dados. Vamos a nossa avaliação do pressuposto.</p>
<p>Primeiro vamos criar um objeto que consiste na diferença entre observadores</p>
<div class="sourceCode" id="cb235"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb235-1" data-line-number="1">diferenca &lt;-<span class="st"> </span>aves<span class="op">$</span><span class="st">`</span><span class="dt">Observador 1</span><span class="st">`</span> <span class="op">-</span><span class="st"> </span>aves<span class="op">$</span><span class="st">`</span><span class="dt">Observador 2</span><span class="st">`</span></a></code></pre></div>
<p>Agora vamos realizar o teste de normalidade da diferença.</p>
<div class="sourceCode" id="cb236"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb236-1" data-line-number="1"><span class="kw">shapiro.test</span>(diferenca)</a></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  diferenca
## W = 0.98173, p-value = 0.9544</code></pre>
<p>De acordo com o teste de Shapiro os dados são normais. Vamos a nossa avaliação pelo teste-t</p>
<div class="sourceCode" id="cb238"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb238-1" data-line-number="1"><span class="kw">t.test</span>(aves<span class="op">$</span><span class="st">`</span><span class="dt">Observador 1</span><span class="st">`</span>,</a>
<a class="sourceLine" id="cb238-2" data-line-number="2">       aves<span class="op">$</span><span class="st">`</span><span class="dt">Observador 2</span><span class="st">`</span>,</a>
<a class="sourceLine" id="cb238-3" data-line-number="3">       <span class="dt">paired =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb238-4" data-line-number="4">       <span class="dt">conf.level =</span> <span class="fl">0.95</span>)</a></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  aves$`Observador 1` and aves$`Observador 2`
## t = -2.1608, df = 19, p-value = 0.04369
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -2.36237491 -0.03762509
## sample estimates:
## mean of the differences 
##                    -1.2</code></pre>
<p>Para a execução do teste-t pareado 2 diferenças podem ser notadas na escrita da função. A primeira consiste no fato de que não utilizamos o til (~), mas sim as variáveis referentes as observações e a segunda é o argumento paired que tem valor lógico (ou seja, verdadeiro ou falso) e indicamos ele como “TRUE” (verdadeiro).</p>
<p>Quanto ao resultado podemos notar que nos é informado que o teste consiste num teste-t pareado e que a diferença entre os observadores é ligeiramente diferente a um nível de confiança de 95%, visto que o “p-value” é próximo à 0,05 e na última linha nos é indicado que a média da diferença das observações é de -1,2. Em outras palavras o teste nos diz que a média das diferenças é diferente de 0, portanto rejeitamos a hipótese nula.</p>
<p>Assim como fizemos anteriormente vamos olhar o resultado em relação a distribuição função de densidade do teste-t (Figura <a href="teste-t-.html#fig:testet-par-ave">4.17</a>). Só devemos lembrar de carregar o pacote “webr” se ainda não foi carregado.</p>
<div class="sourceCode" id="cb240"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb240-1" data-line-number="1"><span class="kw">library</span>(webr)</a>
<a class="sourceLine" id="cb240-2" data-line-number="2"><span class="kw">plot</span>(<span class="kw">t.test</span>(aves<span class="op">$</span><span class="st">`</span><span class="dt">Observador 1</span><span class="st">`</span>,</a>
<a class="sourceLine" id="cb240-3" data-line-number="3">            aves<span class="op">$</span><span class="st">`</span><span class="dt">Observador 2</span><span class="st">`</span>,</a>
<a class="sourceLine" id="cb240-4" data-line-number="4">            <span class="dt">paired =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb240-5" data-line-number="5">            <span class="dt">conf.level =</span> <span class="fl">0.95</span>))</a></code></pre></div>
<div class="figure"><span id="fig:testet-par-ave"></span>
<img src="livroR-1.0_files/figure-html/testet-par-ave-1.png" alt="Curva de densidade representando o valor do teste-t bicaudal para comparação do número de observações de aves por 2 observadores distintos a um intervalo de confiança de 95%. O ponto azul indica o valor do teste." width="672" />
<p class="caption">
Figura 4.17: Curva de densidade representando o valor do teste-t bicaudal para comparação do número de observações de aves por 2 observadores distintos a um intervalo de confiança de 95%. O ponto azul indica o valor do teste.
</p>
</div>
<p>Neste teste em particular como trabalhamos com a diferença entre as observações vamos usar o gráfico de barras para graficar essa diferença.</p>
<div class="sourceCode" id="cb241"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb241-1" data-line-number="1"><span class="kw">barplot</span>(diferenca,</a>
<a class="sourceLine" id="cb241-2" data-line-number="2">        <span class="dt">xlab =</span> <span class="st">&quot;Dias&quot;</span>,</a>
<a class="sourceLine" id="cb241-3" data-line-number="3">        <span class="dt">ylab =</span> <span class="st">&quot;Diferença entre observadores (Observador 1 - Observador 2)&quot;</span>,</a>
<a class="sourceLine" id="cb241-4" data-line-number="4">        <span class="dt">main =</span> <span class="st">&quot;Meu gráfico&quot;</span>,</a>
<a class="sourceLine" id="cb241-5" data-line-number="5">        <span class="dt">names.arg =</span> aves<span class="op">$</span>Dia,</a>
<a class="sourceLine" id="cb241-6" data-line-number="6">        <span class="dt">las =</span> <span class="dv">2</span>,</a>
<a class="sourceLine" id="cb241-7" data-line-number="7">        <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="op">-</span><span class="fl">7.3</span>, <span class="fl">7.3</span>),</a>
<a class="sourceLine" id="cb241-8" data-line-number="8">        <span class="dt">cex.names =</span> <span class="fl">0.9</span>)</a></code></pre></div>
<div class="figure"><span id="fig:bar-dif-ave"></span>
<img src="livroR-1.0_files/figure-html/bar-dif-ave-1.png" alt="Diferença entre o número de observações de aves, por dia, para cada observador" width="672" />
<p class="caption">
Figura 4.18: Diferença entre o número de observações de aves, por dia, para cada observador
</p>
</div>
<p>Para o gráfico acima indicamos em seu comando que faremos um gráfico de barras onde o que será plotado é a diferença no número de observação de aves entre observadores (Figura <a href="teste-t-.html#fig:bar-dif-ave">4.18</a>). O argumento “xlab” indica o nome do eixo x, “ylab” o nome do eixo y, “main” indica o título do gráfico, “names.arg” indica a coluna referente aos nomes das barras (que são os dias), “las” indica se os nomes das barras serão plotados na horizontal ou vertical (o valor 2 indica vertical), “ylim” indica os limites do eixo y e “cex.names” indica o tamanho da letra dos nomes das barras.</p>
<p>As barras para o lado positivo do eixo y indica uma maior observação de aves pelo observador 1 e as barras para baixo indicam um maior número de observações de aves pelo observador 2. Vamos indicar isso no gráfico por meio da função <em>mtext()</em> (Figura <a href="teste-t-.html#fig:bar-dif-ave2">4.19</a>).</p>
<div class="sourceCode" id="cb242"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb242-1" data-line-number="1"><span class="kw">barplot</span>(diferenca,</a>
<a class="sourceLine" id="cb242-2" data-line-number="2">        <span class="dt">xlab =</span> <span class="st">&quot;Dias&quot;</span>,</a>
<a class="sourceLine" id="cb242-3" data-line-number="3">        <span class="dt">ylab =</span> <span class="st">&quot;Diferença entre observadores (Observador 1 - Observador 2)&quot;</span>,</a>
<a class="sourceLine" id="cb242-4" data-line-number="4">        <span class="dt">main =</span> <span class="st">&quot;Meu gráfico&quot;</span>,</a>
<a class="sourceLine" id="cb242-5" data-line-number="5">        <span class="dt">names.arg =</span> aves<span class="op">$</span>Dia,</a>
<a class="sourceLine" id="cb242-6" data-line-number="6">        <span class="dt">las =</span> <span class="dv">2</span>,</a>
<a class="sourceLine" id="cb242-7" data-line-number="7">        <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="op">-</span><span class="fl">7.3</span>, <span class="fl">7.3</span>),</a>
<a class="sourceLine" id="cb242-8" data-line-number="8">        <span class="dt">cex.names =</span> <span class="fl">0.9</span>)</a>
<a class="sourceLine" id="cb242-9" data-line-number="9"></a>
<a class="sourceLine" id="cb242-10" data-line-number="10"><span class="kw">mtext</span>(<span class="dt">at =</span> <span class="dv">4</span>,</a>
<a class="sourceLine" id="cb242-11" data-line-number="11">      <span class="dt">line =</span> <span class="dv">-2</span>,</a>
<a class="sourceLine" id="cb242-12" data-line-number="12">      <span class="dt">text =</span> <span class="st">&quot;Observador 1&quot;</span>, </a>
<a class="sourceLine" id="cb242-13" data-line-number="13">      <span class="dt">side =</span> <span class="dv">3</span>)</a>
<a class="sourceLine" id="cb242-14" data-line-number="14"><span class="kw">mtext</span>(<span class="dt">at =</span> <span class="dv">4</span>, </a>
<a class="sourceLine" id="cb242-15" data-line-number="15">      <span class="dt">line =</span> <span class="dv">-2</span>,</a>
<a class="sourceLine" id="cb242-16" data-line-number="16">      <span class="dt">text =</span> <span class="st">&quot;Observador 2&quot;</span>, </a>
<a class="sourceLine" id="cb242-17" data-line-number="17">      <span class="dt">side =</span> <span class="dv">1</span>)</a></code></pre></div>
<div class="figure"><span id="fig:bar-dif-ave2"></span>
<img src="livroR-1.0_files/figure-html/bar-dif-ave2-1.png" alt="Diferença entre o número de observações de aves, por dia, para cada observador." width="672" />
<p class="caption">
Figura 4.19: Diferença entre o número de observações de aves, por dia, para cada observador.
</p>
</div>
<p>Como podem visualizar a função <em>mtext()</em> indicou os nomes Observador 1 e Observador 2 no lado do gráfico que os representa. O argumento “at” indica a posição em relação ao eixo x, “line” indica a posição em relação ao eixo y, “text” indica o que será plotado e side indica o lado da janela gráfica onde o texto será plotado (3 é na parte superior e 1 na inferior).</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="qui-quadrado-chi.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="final-words.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["livroR-1.0.pdf", "livroR-1.0.docx"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
